### ISSUE TITLE
[FEAT] 数据同步问题

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#12]
你好
我在进行数据同步的时候，发现两个设备的数据同步不过去，自己找了原因，发现，每次打开插件，数据文件就会改动，导致数据文件是最新的，所以每次同步只是当时在使用设备的数据，因为它是最新的

解释一下，a 设备是昨天使用的，我今天第一次打开b设备，结果还是b设备的数据，并没有通知a设备的数据过来，原因是b设备在打开后，recall的数据就变动了，所以a设备的数据就同步不过来

如果要解决这个问题，就要先关掉插件，然后等同步完成再打开插件，这样就可以同步

这样属实不太方便，请问大大可以解决这个问题吗

**Comment by Newdea** [comment]
1.10.1.9 这版已经修改了，只在收到评分时才保存，你试下看是否满足

**Comment by YIRU69** [comment]
感谢，我看了后测试了一下，同步效果，发现如果我电脑改动后，然后同步到手机，手机的csv文件同步过来了，但是复习卡片面板复习数量没有改动，还是之前的
另外我发现csv文件的标签是不支持中文吗，我的标签出现了乱码

![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/48148292/b8e52f8b-d0ed-43cf-aae4-c74452a9c131)

**Comment by Newdea** [comment]
> 手机的csv文件同步过来了，但是复习卡片面板复习数量没有改动

面板的复习数量不是根据这个判断的，是`tracked_files.json`, 同步后重新打开下面板，应该会更新的。

> 另外我发现csv文件的标签是不支持中文吗，我的标签出现了乱码

这个应该是支持的，我电脑上显示是正常的中文(默认UTF-8编码)。你用记事本打开看下。
如果还是乱码，可能是文件编码出问题了。

**Comment by YIRU69** [comment]
明白了，当我在笔记中进行评分的时候 tracked_files.json 文件会有改动，但是如果我只是进行 卡片的改动的话，tracked_files.json是不会改动，只是在 csv  文件中有改动，所以就造成了同步的问题，我卡片的同步没有通过成功

**Comment by Newdea** [comment]
你这个应该是和问题 #14 一样的，晚上我看下具体情况吧

**Comment by zipoopiz** [comment]
> 你这个应该是和问题 #14 一样的，晚上我看下具体情况吧

我的情况是评分后也没有修改 tracked_files.json

**Comment by YIRU69** [comment]
嗯嗯，测试了一下，现在没有这个问题了，谢谢
