### ISSUE TITLE
卡片多的话支持重排吗？

### ISSUE THREAD

**Issue by zipoopiz** [open-spaced-repetition/obsidian-spaced-repetition-recall#13]
在配置项和命令里没有看到这个功能。叶佬的FSRS Optimizer可以做这个事吗？

**Comment by Newdea** [comment]
插件本身不能重排，但有生成复习表格csv文件，可通过[optimizer](https://github.com/open-spaced-repetition/fsrs-optimizer) 方式重排

**Comment by Newdea** [comment]
@L-M-Sherlock  optimizer也只能优化p参数组，没有重排功能吧

**Comment by L-M-Sherlock** [comment]
优化器只是用来生成优化参数的。重排是 FSRS4Anki Helper 插件的功能。具体的代码在这里：https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/main/schedule/reschedule.py
