### ISSUE TITLE
[BUG]安卓手机上复习完成后，重启app，复习记录丢失

### ISSUE THREAD

**Issue by zipoopiz** [open-spaced-repetition/obsidian-spaced-repetition-recall#14]
我看了下手机同步过来的tracked_files.json, due字段和last_review字段好像都差了8个小时
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/8112182/125dc904-37ec-44c3-894b-a30929298023)

**Comment by Newdea** [comment]
正常的，保存的是UTC时间，我们是东8区就刚好相差8小时，不影响的。

你说的
> 复习记录丢失

就是指这个么，那这是没有问题的

**Comment by zipoopiz** [comment]
电脑端好像也有这个问题。我这边是复习完了直接关掉应用的，看了下tracked_files.json的修改日期，好像没有写入。

**Comment by zipoopiz** [comment]
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/8112182/146b94be-63fe-40e5-abc6-14eddcf30074)
ob_revlog的修改时间应该是对的，就是我复习完卡片的时间。但是tracked_files.json的修改日期不太对

**Comment by zipoopiz** [comment]
> 正常的，保存的是UTC时间，我们是东8区就刚好相差8小时，不影响的。
> 
> 你说的
> 
> > 复习记录丢失
> 
> 就是指这个么，那这是没有问题的

不是的，复习记录丢失是指我复习完卡片后，再打开应用，会让我重新复习

**Comment by Newdea** [comment]
嗯，那我晚上看下具体啥情况

**Comment by Newdea** [comment]
刚更新的一版，已经修复了
