### ISSUE TITLE
笔记复习功能，标签化管理的问题

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#15]
首先十分感谢您对于obsidian内的间隔重复功能上的贡献！
对于这个插件的笔记复习使用上我遇到一点疑惑，我的复习场景是对某一知识领域的内容进行集中复习，于是我的复习tags里加的就是类似#数学 #政治这样的内容。
<img width="768" alt="截屏2023-09-09 16 44 59" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/6d0ed1f0-6995-4c6e-851c-a59583d1aa18">
但是在试着想要打开政治这个内容进行复习时我不得不在#政治下属的所有标签里进行选择。请问这个是否能更改成原插件那样？
<img width="720" alt="截屏2023-09-09 16 45 41" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/6ec8106c-825f-4973-8443-b2fedfbf59f3">
当我在设置里加的是#政治 时，我在打开一篇笔记开始复习时可以直接对#政治 下的所有笔记进行复习，当我在设置里加的是#政治/xxx 时，我就直接可以对#政治/xxx 的及其下属标签的所有笔记进行复习。

**Comment by Newdea** [comment]
可以的，基本没有使用多级标签，没想到会导致这个问题，我后续改下

**Comment by Newdea** [comment]
刚发布的新版已经解决了这个问题
