### ISSUE TITLE
[BUG]当删除笔记文件，同步混乱

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#16]
你好，我遇到一个问题
描述：当我将一个复习笔记在电脑端删除，之后进行同步到云存储，然后再到手机上进行同步，发现手机会提示“untrack 1items”，然后我的电脑的复习记录并不会同步到手机，而是手机的复习记录为最新

我想这个问题还是有问题的，可能因为插件检测到复习笔记删除了，所以同步更新了插件的数据文件，导致手机的数据文件是最新的，因此电脑端的复习数据就没有更新过来

请问这种问题可以解决吗

**Comment by Newdea** [comment]
电脑上删除时，就已经untrack了，手机提示是调试日志（实际没有修改数据，那部分功能还没想好要怎么改，就打印出日志了，不影响正常使用）。

> 我想这个问题还是有问题的，可能因为插件检测到复习笔记删除了，所以同步更新了插件的数据文件，导致手机的数据文件是最新的，因此电脑端的复习数据就没有更新过来

- [ ]  这个你要看tracked_files.json 文件的修改日期才能确定，如果是和电脑端的修改日期一致，就是同步成功了。
上次插件更新后，是可以正常同步的。

**Comment by YIRU69** [comment]
我说的不清楚，我电脑删除了复习的文件，电脑端是更新了tracked_files.json文件对吧。然后我手机开始同步，开始同步的是要删除一些复习文件，这时候的手机端的tracked_files.json是没有同步电脑端的，所以手机端又一遍根据同步过来删除的复习文件进行 untrack，所以这时候手机端的tracked_files.json就是最新数据，这样我应该说清楚这个流程吧
所以我一些电脑端tracked_files.json改动的数据文件，其实并没有能同步到手机端

**Comment by Newdea** [comment]
我知道你的意思，但是不是最新，不是看手机弹出的提示，要看文件的修改日期。 或者看统计图（命令：查看数据）当天的复习数据应该是和电脑的一样的。
> 电脑上删除时，就已经untrack了，手机提示是调试日志（实际没有修改数据，那部分功能还没想好要怎么改，就打印出日志了，不影响正常使用）。

我下版把这个提示改掉吧，以免误导大家。

---
如果按这个方法确认确实没有同步，那就真有问题了（我这边操作几次确认都是有同步的，用的是win10, syncthing, android手机），你也提供下同步方式。


---
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/daed6666-2fb3-41e4-82b3-8c3e4aa62bd1)

---
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/3107b35a-8832-4549-944a-c739f8afce7e)
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/6fa37713-2cc1-4e96-9bfb-60f63be16300)

**Comment by YIRU69** [comment]
我的同步是用 remotely save + 腾讯 cos 的方式

**Comment by YIRU69** [comment]
可能这种同步方式没有syncthing 速度快，我的笔记比较多，所以比较慢，就会出现这种同步的问题

**Comment by Newdea** [comment]
额，我是**希望你能再确认下**的，不一定是同步问题。

> 但是不是最新，不是看手机弹出的提示，要看文件的修改日期。 或者看统计图（命令：查看数据）当天的复习数据应该是和电脑的一样的。

这个清单任务你做一遍（你应该也能直接点击这个清单，修改任务状态的）：
1. [ ] 先看 电脑和手机的tracked_files.json 文件的**修改日期**一致（假定是14:00）；
2. [ ] 查看统计图表（命令：**查看数据**）当天的复习数据（假定学习0，复习0）；
3. [ ] 在电脑随便新建测试文件（内容含有多个测试卡片），加入复习标签，然后复习这几个卡片（命令：复习此笔记中的卡片）；
4. [ ] 查看统计图表（命令：查看数据）当天的复习数据（假定学习3，复习0），这里已经和第2步不同了；
5. [ ] 删除这个测试文件；
6. [ ] 查看 电脑的tracked_files.json 文件的修改日期（假定是14:10）；
7. [ ] 等两分钟，手机上 打开OB，同步，按你说的应该会有弹窗提示“untrack 1items”（ 看问题描述，你是在这步认为同步出问题的），等同步完成（remotely save 会有提示吧，好久没用这个插件记不清楚了）；
8. [ ] 在手机文件管理器中查看 tracked_files.json 文件的修改日期，如果是（假定是14:12）那就是确实同步出问题了，如果是和电脑一致的（是14:10）那就是同步正常OK的；
9. [ ] 也可以在手机上看 统计图表（命令：查看数据）当天的复习数据，如果是（学习0，复习0）那就是确实同步出问题了，如果是（学习3，复习0）那就是同步正常OK的。

希望能看明白我的意思

**Comment by YIRU69** [comment]
好的，我明天做个测试看看

**Comment by YIRU69** [comment]
我确认了，电脑同步过来的 tracked_files.json 文件，到手机端时间并不是电脑端的时间，确认是手机根据文件增减先改了 tracked_files.json 文件，再进行的同步，所以电脑端并没有同步过来

**Comment by YIRU69** [comment]
我使用了增减3个文件的方式来进行测试，发现电脑端到手机端的同步是没有问题的，我上面发生的情况是更改了600个文件，可能是不同的情况，不管怎么说，这个更改过来的情况不会频繁发生，非常感谢你对这个问题的关注和耐心的解答，我认为这个问题对我来说算解决了，再次谢谢你

**Comment by Newdea** [comment]
那后续再出现的话，再反馈吧。

也可以用plugin group插件，让remotly save先启动，让这个间隔重复插件启动晚些
