### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CRISUM** [open-spaced-repetition/obsidian-spaced-repetition-recall#17]
**Describe the bug**
obsdian更新后整个插件无法使用：即无法自动创建卡片，无法复习，无法读取之前的卡片与复习数据。

**To Reproduce**
额就是更新obsdian之后，obsdian只有原有功能，FSRS相关功能丢失。

**Expected behavior**
恢复原有功能，如果可以希望能恢复之前的学习数据

**Screenshots**
![新版界面](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/25550350/088de1f1-fd6f-47f9-9070-71c900407e32)
![插件使用最新的.11版本](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/25550350/2eb78c08-d5c5-4c81-8641-8746f31b9889)

**Versions (please complete the following information):**

-   OS: [Windows10]
-   Obsidian version: [v1.4.14]
-   Plugin version: [v1.10.1.11]
-   If on desktop, Installer version: [run `this.navigator.appVersion` on the developer console, e.g. `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"`]
额这个插件是直接放在笔记下的文件夹的。。。没安装器啊。如果是obsdian的话已经把安装器删了

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by Newdea** [comment]
ob软件更新不影响，应该是你没有设置好。我目前OB最新的1.4.16上可以正常使用

**Comment by Newdea** [comment]
这个问题还在么，我先关了。如果还在请回复
