### ISSUE TITLE
[FEAT] 隐藏command "Reset data"或者增加进一步确认的

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#18]
在探索这个插件的时候，不小心点击”reset data"这个命令，一切回到了原点，所有记录都消失了

**Describe the solution you'd like**
希望能够隐藏这个命令或者对这个命令增加进一步确认的

**Comment by Newdea** [comment]
这个选项关闭就不会显示在命令面板里了

**Comment by dryezl** [comment]
我指的命令是指 打开command palette (快捷键Ctrl-P）搜索 reset data 显示的命令 
这个命令作用太大，会重置卡牌复习数据，希望能够加上进一步确认的。
不好意思，是我没有说清楚。

**Comment by Newdea** [comment]
是的，那个设置关闭后，重启ob就不显示了

**Comment by dryezl** [comment]
感谢
