### ISSUE TITLE
卡片数据使用在笔记文件中对应卡片段插入一个id做索引的讨论（投票）

### ISSUE THREAD

**Issue by liilei** [open-spaced-repetition/obsidian-spaced-repetition-recall#20]
我理解目前的做法是用lineNo做为id，是否可以学习obsidian-spaced-repetition的做法，在笔记文件中插入一个字段（相比osr这个字段是不变的）做为id。这样就可以解决行号变化的问题了

**Comment by Newdea** [comment]
有考虑过，但这样会在笔记内添加额外内容，就有点不想这样做。
目前是以行号和hash做索引（修改时会同步更新），卡片内容没有大变动就基本不会出错。

**Comment by liilei** [comment]
> 有考虑过，但这样会在笔记内添加额外内容，就有点不想这样做。 目前是以行号和hash做索引（修改时会同步更新），卡片内容没有大变动就基本不会出错。
卡片过程中我还是会调整，还是会有变化的，不知道其它同好是如何使用的。只是编辑状态下可见的固定内容我认为影响不大

**Comment by YIRU69** [comment]
我赞成以文中的id作为LineNo，目前以文件位置作为LineNo，有一个很不好的问题，就是文件追踪以及定位，如果我复习的文件移动了位置 ，那么相当于我的复习数据要重新定位了

大大是否意味之前sr采取在yaml中添加了的这种信息太多导致文件笔记的信息冗余，那其实只识别yaml的id字段是一个不错的选择

**Comment by Newdea** [comment]
> 我赞成以文中的id作为LineNo，目前以文件位置作为LineNo，有一个很不好的问题，就是文件追踪以及定位，如果我复习的文件移动了位置 ，那么相当于我的复习数据要重新定位了

插件有使用文件移动和重命名事件函数，在OB中移动和重命名文件，复习数据会跟随更新，不会丢失的。


> 大大是否意味之前sr采取在yaml中添加了的这种信息太多导致文件笔记的信息冗余，那其实只识别yaml的id字段是一个不错的选择

卡片的id是需要以块为单位（即两个空行之间的内容），yaml的id字段是文件的，如果这文件有多个卡片就解决不了。

大家投个票吧（点这个回复对应的表情符号就行）：
👍  支持在文本块后添加id（效果就像uri插件在行后添加的uri `^id1234`），会修改笔记内容；
😄 保持当前状态，采用行号和hash索引卡片，不修改笔记内容（推荐这个方式）；

有其它想法可继续回复讨论。

**Comment by YIRU69** [comment]
> 支持在文本块后添加id（效果就像uri插件在行后添加的uri ^id1234），会修改笔记内容；

我指的不是在这个操作，我卡片的我觉得不需要改，主要是笔记的复习，我觉得可以加上对yaml 区id字段的识别，之前的sr也是用的这种方式，他的日期都是通过yaml区的字段去计算的，我觉得可以结合一下，用yaml区的id字段做定位，然后数据还是保存在一个文件里面

**Comment by Newdea** [comment]
只是移动更改位置，还是可以正常复习的

**Comment by Newdea** [comment]
目前这个方案（行号和hash）只要不是同时修改卡片行号和内容，应该没有多少错误识别吧。修改后，**需复习一次**笔记或卡片，更新的数据才会保存（可能大家有时没有这个操作，才会把已经复习的当新卡片）。

**Comment by YIRU69** [comment]
> 目前这个方案（行号和hash）只要不是同时修改卡片行号和内容，应该没有多少错误识别吧。修改后，**需复习一次**笔记或卡片，更新的数据才会保存（可能大家有时没有这个操作，才会把已经复习的当新卡片）。

有呀，就是这种方案（现在的），如果我在笔记中的卡片中间，添加卡片，或者增加多行，那么修改后的卡片全部都成了新卡片，所以一直有这种需求

**Comment by YIRU69** [comment]
渐进笔记卡片，是需要进行不断的更新和变动的，如果写了一个卡片不改动，对我来说，这种情况真的不常见，因为我的学习是越来越有深度的，所以卡片不可避免会改动。总之，希望大大可以增加，通过id字段进行标记。

我倾向与和 sr 软件的那种标志，这样不管行号还是内容，我都可以更改，而不会改变同一个文件中的其他卡片

**Comment by dryezl** [comment]
依然有这个需求，多个卡片在同一个笔记中，修改前面的卡片，就会导致后面卡片变动的。
我的更改想法如下的
https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/52#issuecomment-2209841519

**Comment by Newdea** [comment]
尝试改了一版，在沙盒里试用感觉还OK，你们试下看，有问题欢迎反馈。
设置是默认关闭的
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/b69dd789-2630-4922-8fa2-5e7f31211e1a)


！！！注意：
由于会在卡片后追加blockid，即会修改原笔记文件内容，
请**先备份**笔记库，以免破坏重要数据；或
在沙盒中试用
[main_addCardBlockID.zip](https://github.com/user-attachments/files/16162828/main_addCardBlockID.zip)

**Comment by dryezl** [comment]
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/47209925/af1b2643-2991-4d61-84d3-0a1c31ec9b07)
有些卡片会产生多个编码的
有一些卡片会被识别为新卡片，即原本的学习记录被重置，查看这个卡片的信息时，发现没有相关学习记录的
可不可以考虑在卡片后增加类似原本SM-2的那种类型id呢？比如像`!<--fsrsID: -->`

**Comment by YIRU69** [comment]
> 比如像 `!<--fsrsID: -->`

赞成这种形式

然后可以支持在卡片的末尾行添加标志信息，这样不会破坏卡片的结果，至于会破坏笔记的结构还好，因为在笔记中，卡片是的一个模块化的东西，其实可以的话甚至可以把卡片成为一个笔记，但那样做的代价就是笔记太多，总之，把卡片当作整体模块进行操作是可行的思路。

**Comment by Newdea** [comment]
> 有些卡片会产生多个编码的

截图是否完整，你这是一块文本中（即两个空行之间的内容）有多个挖空么

**Comment by dryezl** [comment]
下面是该笔记前后几行。可能是obsidian还在对笔记进行索引的时候（因为我把原本的笔记复制了一份到另外一个文件夹），我就启用插件，对卡片进行标记吧。  

```txt
「线索」不应该产生什么效果？
?
允许你不加回忆地推断问题 ^9hjvi1


精细编码：如果你可以让信息==与其他记忆产生联系==，信息会更容易回忆。 ^etlcon ^b0tx1v ^1yxj1z ^i4x5zj ^5hrt6l ^fgqcj5 ^uk38jm ^ns0mvl ^fpb2r1 ^nczf2k ^awqdky ^
soxyq0 ^p54ryv ^fk882a

「精细编码 （elaborative encoding）」
?
将信息与其他记忆相关联，它会变得更好回忆 ^guq9kc

elaborative encoding如何让信息更好回忆
?
将其与其他记忆相关联 ^2xrqfo
```

**Comment by Newdea** [comment]
@dryezl 这个问题是怎么出现的，我试了几次都是正常的。能否提供下步骤及测试库（也许下面这个新的解决了）。


识别为新卡片的问题，这个改了
[main_addCardBlockID_fix.zip](https://github.com/user-attachments/files/16179635/main_addCardBlockID_fix.zip)

**Comment by YIRU69** [comment]
反应一个问题，当我的卡片中间有一行文字，这个就没有自动添加 blockid .

我的文本是这样的,可以看出来，A1 是添加成功了，但是A2就没有添加成功

```

-  [p. 52]( zotero://open-pdf/library/items/8PA8DBSG?page=52&annotation=6YIACWEK)

Q1
%%↓↓↓%%
A1 ^eh7711

-  [p. 53]( zotero://open-pdf/library/items/8PA8DBSG?page=53&annotation=VJQEWLJU)
 
Q2
%%↓↓↓%%
A2
```

报错是：
```
plugin:obsidian-spaced-repetition-recall:9307 updateQuestionText: Text not found: -  [p. 53]( zotero://open-pdf/library/items/8PA8DBSG?page=53&annotation=VJQEWLJU)
(2)  (1988 年试题) 若函 in note: ---
UID: "20240303200256244"
title: 
fileClass: 
aliases: 
tags:
  - 
  -
```
![image](https://github.com/user-attachments/assets/1d6c3c4a-e57d-4263-8e26-96067b5b6631)

**Comment by dryezl** [comment]
@Newdea fix版本的也会有类似的问题的。下面是一个测试库。vim或者其他编辑器打开`如何写出好卡片.md`文件，里面是没有block id的。如果用obsidian打开，因为插件已经设置加上block id，会给卡片块加上id。有一些会加上多个id的。
[note_test_2.zip](https://github.com/user-attachments/files/16185924/note_test_2.zip)

**Comment by Newdea** [comment]
@dryezl 内容重复导致的，尝试修复了。
![image](https://github.com/user-attachments/assets/ab43c135-06a6-49c9-842c-3ab705901821)

@YIRU69 删除空白内容引起的，下边这版修复了
[main_addCardBlockID_fix2.zip](https://github.com/user-attachments/files/16195360/main_addCardBlockID_fix2.zip)

**Comment by dryezl** [comment]
@Newdea 
[main_addCardBlockID_fix2.zip](https://github.com/user-attachments/files/16195360/main_addCardBlockID_fix2.zip)这个文件有问题的。浏览器或者wget下载，microsoft defender会查杀，直接删除的。

**Comment by Newdea** [comment]
没遇到过，和上个文件基本一样的，就是改了几行代码。





---原始邮件---
发件人: "James ***@***.***&gt;
发送时间: 2024年7月13日(周六) 上午6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] 卡片数据使用在笔记文件中对应卡片段插入一个id做索引的讨论（投票） (Issue #20)




 
@Newdea
 main_addCardBlockID_fix2.zip这个文件有问题的。浏览器或者wget下载，microsoft defender会查杀，直接删除的。

**Comment by YIRU69** [comment]
目前用的没有什么问题，非常感谢

**Comment by YIRU69** [comment]
@Newdea blockid 的生成是否可以自定义命名规则，比如前缀和时间戳，便于以后追踪

**Comment by Newdea** [comment]
先确保基本功能走得通，后续可以按命名规则生成，但blockid是有要求的，下面是Obsidian官方定义的要求：
https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note

@YIRU69 你说的规则能举个栗子么

**Comment by YIRU69** [comment]
增加前缀+时间，比如 数学笔记 `^math-2024070208572399` 这个格式 前缀加时间格式 `YYYYMMDDHHmmssSS` 或者有其他

**Comment by dryezl** [comment]
搞不懂为什么查杀的，直接下载js是没有问题的。
迟一点测试一下完全的笔记库。之前的简单笔记库是没有问题的。

**Comment by dryezl** [comment]
请问这个id索引是否可以另起一行呢？
目前id是直接跟在语块的后面的，导致代码块渲染有问题的。 

````txt 

foo bar
?
```bash
ls -lht 
``` ^asdfasdf

foo bar2
?
test

````

上面文档在obsidian里面渲染是很奇怪的。
![image](https://github.com/user-attachments/assets/7fd08b39-5a61-4dc5-8fd8-c7925614d718)

**Comment by Newdea** [comment]
是应该另起一行的

**Comment by dryezl** [comment]
当连续两个的相同语块出现时，插件（1.12.4.8）会不停给第一个语块增加markdown id。
这是复现的测试库。
[note_all_test.zip](https://github.com/user-attachments/files/16343221/note_all_test.zip)

我觉得这个可能不是bug，而是feature，有助于发现重复的卡片。
