### ISSUE TITLE
ob_revlog.csv没有记录卡片review_state为0的情况

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#21]
**Describe the bug**
我用[fsrs-optimizer](https://github.com/open-spaced-repetition/fsrs-optimizer/tree/main)优化复习数据（ob_revlog.csv)时，程序报错。部分报错信息如下
```txt
Ratio of `again`, `hard`, `good` and `easy` ratings for new cards: 0.00, 0.00, 0.00, 0.00
probabilities do not sum to 1
Failed to process /content/ob_revlog.csv
```
重新设置空白vault，下载[obsidian-spaced-repetition-recall](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/releases/tag/1.10.1.11)。

卡牌复习之后，ob_revlog.csv没有review_state为0的记录 

如果没有这个记录的话，意味着这个卡片不能成为优化的有效卡片。

              每张卡片的复习数据的第一条的review_state是否为0

_Originally posted by @L-M-Sherlock in https://github.com/open-spaced-repetition/fsrs-optimizer/issues/13#issuecomment-1670838113_

**Comment by L-M-Sherlock** [comment]
你的数据发我一份，我看看这个bug是不是optimizer那边也有问题。

**Comment by dryezl** [comment]
这是优化时使用的数据，[ob_revlog.csv](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/files/13211927/ob_revlog.csv) 和使用的[代码](https://colab.research.google.com/drive/1_bUXeCZ1QHcINlqZqhV0i9MJVjjodP2b?usp=sharing)

**Comment by Newdea** [comment]
> 你的数据发我一份，我看看这个bug是不是optimizer那边也有问题。

应该是插件的问题，数据记录，新增卡片时没有记录到表格中。只在复习时才有，而第一次复习，卡片状态就会从新卡片（0）变成学习中（1）。

新卡片的时间用处应该不大，只有在开始重复时才有意义。
optimizer中能不能从判断0改为判断0或1，插件这边新增时就记录的话可能会有重复混乱不太好判断状态，目前只是在复习反馈时才记录。

**Comment by Newdea** [comment]
代码中是用的复习后的review_state，下版更新会改用复习前的review_state（即直接采用ReviewLog内的数据），就可以解决这个问题了

```
//Get the review log after rating `Good`:
review_log = scheduling_cards[rating.Good].review_log
```

**Comment by dryezl** [comment]
请问这个下一版是哪个软件呢？[obsidian-spaced-repetition-recall](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/releases)还是[fsrs-optimizer](https://github.com/open-spaced-repetition/fsrs-optimizer/tree/main)呢？

**Comment by L-M-Sherlock** [comment]
前者。
