### ISSUE TITLE
使用教程

### ISSUE THREAD

**Issue by Newdea** [open-spaced-repetition/obsidian-spaced-repetition-recall#23]
#### case:没有使用原SR插件，直接使用这个插件
推荐设置项
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/a22d23df-5d11-4b19-9007-e1530e2808be)

算法对应的具体参数设置，可参考[FSRS v4](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm#fsrs-v4)

其他设置项根据说明自行设置即可。

通过命令行进行复习
或电脑端，点击状态栏/右侧边栏的笔记就可以复习笔记，点击左侧边导航栏的卡片就可以复习

其他，参照[@st3v3nmw's ReadMe](https://github.com/st3v3nmw/obsidian-spaced-repetition#readme)  & [recall plugin's ReadMe](https://github.com/martin-jw/obsidian-recall)

#### case:从原SR插件转入
建议步骤：
1. 先关闭原插件，避免冲突。
2. 备份笔记库（因在设置中修改DataLocation后，会删除笔记内容中的复习信息，另存到 单独文件 tracked_files.json。 ）
3. 设置卡片复习标签、笔记复习标签
4. 如果是想用FSRS算法，需要按上述推荐设置数据位置、算法。

---
#### 添加笔记
可在笔记中添加复习笔记对应的标签，或通过命令行/菜单栏[tracking notes](https://github.com/martin-jw/obsidian-recall#tracking-notes)。
通过命令行/菜单栏untrack Note可取消。

添加文件夹中的笔记，可在文件夹上右键， (un)track All Notes
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/163f397c-cc8f-49a6-ab6f-cb929cf91d2d)

#### 添加卡片
在笔记中添加复习卡片对应的标签，或设置中将复习笔记转换为卡片组，或设置中将文件夹转换为卡片组，按照[以下说明](https://github.com/st3v3nmw/obsidian-spaced-repetition#features) 制作卡片。

- [Single-line style](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#single-line-basic-remnote-style) (`Question::Answer`)
- [Single-line reversed style](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#single-line-reversed) (`Question:::Answer`)
- [Multi-line style](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#multi-line-basic) (Separated by `?`)
- [Multi-line reversed style](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#multi-line-reversed) (Separated by `??`)
- [Cloze cards](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#cloze-cards) (`==highlight==` your cloze deletions!, `**bolded text**`, or `{{text in curly braces}}`)

#### 复习笔记
通过命令行，或电脑端点击状态栏/右侧边栏的笔记就可以打开复习笔记。通过命令行、悬浮栏或菜单栏可反馈记忆程度

#### 复习卡片
通过命令行，或电脑端点击左侧边导航栏的卡片就可以复习。
通过命令行，可集中（CRAM）复习/正常复习当前/所有笔记内的卡片（若有）

集中复习（CRAM）模式，不更新复习数据。

#### 查看数据统计
通过命令行，`SR 查看数据`

#### 查看复习信息
通过命令行，`SR Item Info`,可查看当前/所有笔记的复习信息

#### 实验性功能
不建议使用！！！
不建议使用！！！
**不建议使用！！！**

打开设置Logging-->调试信息，即可在命令行中使用以下功能（日常使用不建议打开）。

输出数据项Print Data： 在调试窗口中输出数据

重置数据Reset Data：删除所有复习数据；

更新数据项Update Items： 更新数据中的无效数据为默认数据。

清除无效数据Prune Data： 清除数据中的无效数据，会导致数据项id修改，进而会影响Fsrs的optimizer无法有效处理部分数据。

**Comment by MrHorse055** [comment]
请问`SR Item Info`是指哪项命令？我未能在插件的命令中找到相似条目
此外，请问命令中的`Build Queue`是起什么作用的？
我当前的插件版本为1.10.1.11

**Comment by Newdea** [comment]
尴尬了，下一版有，目前还在改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月18日(周六) 晚上7:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] 使用教程 (Issue #23)




 
请问SR Item Info是指哪项命令？我未能在插件的命令中找到相似条目
 此外，请问命令中的Build Queue是起什么作用的？
 我当前的插件版本为1.10.1.11

**Comment by dryezl** [comment]
请问这个可不可以加到readme.md里面呢？方便后续人看的

**Comment by Newdea** [comment]
在整理，后续会加进去的

**Comment by Newdea** [comment]
已经更新到readme中了，这里就不再更新了。

https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/blob/dev-master/docs/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B.md

https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/blob/dev-master/docs/usage.md
