### ISSUE TITLE
[FEAT] 是否可以为笔记复习增加‘重来’按钮的快捷键

### ISSUE THREAD

**Issue by u2003** [open-spaced-repetition/obsidian-spaced-repetition-recall#25]
感谢您的开发！换用frss算法之后感觉很好，不过好像快捷键还是原来的三个，只有简单、记得、困难，感觉不是很统一，如果能给重来也加上自定义快捷键就更好啦！

**Comment by Newdea** [comment]
这个没有必要吧，fsrs的重来就几分钟，对笔记复习来说，这个间隔太短，基本不用

**Comment by Newdea** [comment]
嗯，也是的，那就下版加上吧。
右键菜单栏就不加了，还保持原状态。


其实，用悬浮栏也很方便的😅



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月1日(周五) 晚上11:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [FEAT] 是否可以为笔记复习增加‘重来’按钮的快捷键 (Issue #25)




 
要是隔了一段时间没被安排复习（两周一个月之类）或者有一段时间没按时清空 就要重来啊🤣
