### ISSUE TITLE
[FEAT] 请问可以加上一个toggle是否显示review bar和toggle是否显示日期的command

### ISSUE THREAD

**Issue by u2003** [open-spaced-repetition/obsidian-spaced-repetition-recall#27]
我个人更喜欢使用快捷键，觉得更加快捷，不太喜欢下面多出来的两个按钮觉得不太对称且有一点美观，请问是否可能加上toggle是否显示review bar和toggle是否显示日期的command呢？十分感谢！

**Comment by Newdea** [comment]
当时这样做，是考虑到使用方便，没有考虑美观性。
- 如果放命令中，会不会导致命令中的杂项过多，显得有些乱呢？
- 放设置中的话，使用又有些不方便（我有些笔记会希望过几天再看到，就需要显示间隔；另一些笔记就是回顾，不想看到间隔），而在这个过程中如果编辑笔记，就要关闭浮栏。）

怎么处理好些呢

**Comment by u2003** [comment]
对我来说放在command没有问题诶 毕竟本来就够多了 多这两个不多 少这两个不少 并且我觉得用户有commander插件 如果需要频繁切换可以自行把command放到编辑器菜单或者status bar等等 至于多出来的两个按钮 对我来说我可以自己写css snippet隐藏掉 综上 我的感觉是可以加设置项让用户自己决定开不开按钮 但是不管开不开按钮都有command可以切换是否显示floating bar和时间

**Comment by Newdea** [comment]
想到个方案，
第二行的两个按钮可以直接取消，电脑上通过右键然后弹出菜单来设置显隐间隔、关闭。
手机上可以通过长按和上滑操作

**Comment by u2003** [comment]
取消按钮放到右键菜单的话是可以的，会顺便加上command嘛，我觉得加上command会挺灵活的，用户自定义空间比较多

**Comment by Newdea** [comment]
这个真没有必要吧，用浮栏就在用鼠标，点点点就好了。如果用自定义用快捷键，也不会用浮栏，也就用不到这两个功能了。

**Comment by u2003** [comment]
有道理诶，那我觉得右键浮栏弹出菜单来控制是否显示时间和浮栏挺好的！
