### ISSUE TITLE
spaced repetition数据导入spaced repetition recall后，复习卡片时仍只有“较难/记得/简单”三个选项

### ISSUE THREAD

**Issue by xiongdy54** [open-spaced-repetition/obsidian-spaced-repetition-recall#28]
作者你好！
我按照使用指南中的描述将spaced repetition中的data.json复制到spaced repetition recall后成功切换到了fsrs算法！
但是当我复习卡片时仍只有“较难/记得/简单”三个选项，没有插件设置里所显示的“重来”选项，请问这种情况该如何解决呢？

**Comment by xiongdy54** [comment]
抱歉，我新建了一个库，把刚下载的spaced repetition recall放进去也是没有“重来”选项的，这才知道本来就没有这个选项，是我误会了🫢不好意思

**Comment by Newdea** [comment]
卡片复习是按原插件的界面来的，重来 在上面的菜单栏那几个按钮里

**Comment by xiongdy54** [comment]
我明白了，谢谢回复
