### ISSUE TITLE
[BUG] 更新了1.10.53，插件无法正常运行

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#30]
```
lugin:obsidian-spaced-repetition-recall:11646 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')
    at _Queue.push (plugin:obsidian-spaced-repetition-recall:11646:11)
    at _DataSyncer.syncRCDataToSRrevDeck (plugin:obsidian-spaced-repetition-recall:9591:17)
    at _SRPlugin.sync_Algo (plugin:obsidian-spaced-repetition-recall:28578:35)
    at _SRPlugin.sync (plugin:obsidian-spaced-repetition-recall:28381:18)
    at eval (plugin:obsidian-spaced-repetition-recall:28334:22)
```
上面是报错，不知道什么问题，不能正常使用了，使用命令没有反应

**Comment by YIRU69** [comment]
回退一个版本就没有问题了

**Comment by YIRU69** [comment]
也有可能是ob的问题，我是因为ob更新到 1.5.2 这个问题就出现了，如果没办法复现可能是版本的问题

**Comment by Newdea** [comment]
看报错确实是插件问题，下版修复。
重启插件有可能就正常了

**Comment by YIRU69** [comment]
重启插件了，没有用

**Comment by Newdea** [comment]
嗯，那就下版修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月13日(周三) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [BUG] 更新了1.10.53，插件无法正常运行 (Issue #30)




 
重启插件了，没有用

**Comment by Newdea** [comment]
这版新的应该解决这个问题了

**Comment by YIRU69** [comment]
@Newdea 可能正常运行了，请问，新版本在浮动复习选择框里，把时间图标和叉叉图标的功能都去掉了吗？我觉得这挺好用的呀

**Comment by Newdea** [comment]
都在的，在问题 #27 上有聊过
文档也更新了[使用说明](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/blob/dev-master/docs/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B.md#%E5%A4%8D%E4%B9%A0%E7%AC%94%E8%AE%B0)
