### ISSUE TITLE
How to set up synchronization items if I want to use fsrs algorithm?

### ISSUE THREAD

**Issue by invisprints** [open-spaced-repetition/obsidian-spaced-repetition-recall#31]
In the fsrs setting, you recommend storing the data files in the plugin folder. However, it will cause an unexpected problem when I use the spaced repetition both on the mobile and PC.

The settings of the plugin on the mobile and PC are a little bit different. Specifically, we need different parameters about "Flashcard Height Percentage" and "Flashcard Width Percentage" for better display.

I tried the Obsidian official sync and [obsidian livesync ](https://github.com/vrtmrz/obsidian-livesync). However, maintaining data file synchronization whilst preventing the synchronization of plugin configurations presents a considerable challenge. Could you propose any effective strategies?

**Comment by Newdea** [comment]
> The settings of the plugin on the mobile and PC are a little bit different. Specifically, we need different parameters about "Flashcard Height Percentage" and "Flashcard Width Percentage" for better display.

you could just use mobile settings, or store `trackedfiles.json` to vault root directory without  synchronizing data.json file.

**Comment by invisprints** [comment]
I tried to set the tracked_files.json in the vaults folder, but it reverted back to the plugin folder when I restarted the obsidian. It seems like a bug.

**Comment by Newdea** [comment]
move it from settings --> Data Location

![Selection_001](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/c2d0340b-93e9-491f-89bc-39875219f212)

**Comment by invisprints** [comment]
Sure, as you can see in the video I recorded. Even if I switch the data location, it will revert to the previous one after I restart the obsidian.

I create a new vault to address it.

https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/15833553/c1a0937b-aade-41ed-9c91-955ecc67e038

**Comment by Newdea** [comment]
啊，，，
我刚自己试了下，是有这个问题，应该是设置后没有保存更新的设置项。
你暂时可以先修改位置后，再改下别的设置项，比如 卡片高度之类，然后就可以保存设置项了。

后续我会更新一版修复这个问题。
