### ISSUE TITLE
[BUG] 当我删除复习标签，右侧的面板上这个笔记并没有untrack

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#32]
当我删除复习标签，左侧的面板上这个笔记并没有untrack

我进行了测试，我自己在手动删除了复习标签，按道理应该会 untrack 这个卡片，但是并没有生效，我自己重启了一些插件，还是一样的效果，我进行笔记复习的时候，这个删除复习标签的笔记还存在
我使用 untrack note 命令也无法生效

**Comment by YIRU69** [comment]
[1.zip](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/files/13770040/1.zip)
这是一个测试文件

**Comment by YIRU69** [comment]
版本用的是最新的插件，和最新版的ob

**Comment by Newdea** [comment]
左侧面板？？？


删除笔记里的标签后，需要再手动untrack下，应该就没有了
这一块是从recall合并过来的功能，有这样的后遗症😅





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月26日(周二) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [BUG] 当我删除复习标签，左侧的面板上这个笔记并没有untrack (Issue #32)




 
版本用的是最新的插件，和最新版的ob

**Comment by YIRU69** [comment]
说错了，右侧面板，我手动untrack没有作用

**Comment by YIRU69** [comment]
显示`It is tages file, can't untrack by this. You can delete the #review tag in note file. `
但是我已经删除了标签，还是没有用

**Comment by Newdea** [comment]
可以从命令行或菜单栏，untrack

![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/6e093960-6a84-4c14-ab40-f4d313bf2f2a)

**Comment by YIRU69** [comment]
我是这么做的，但是没有作用，显示It is tages file, can't untrack by this. You can delete the #review tag in note file.

**Comment by YIRU69** [comment]
导致这个问题可能是因为 我的这个文本的笔记包含了两种标签，一种是复习标签，一种是卡片标签，我的#review是复习标签，我删除了复习标签，自己的笔记还存在卡片标签，运行`untrack note`命令，就会失效，显示`It is tages file, can't untrack by this. You can delete the #review tag in note file. `
当我把卡片标签也删除，才成功

**Comment by YIRU69** [comment]
请问，我`untrack`成功了，自己的右侧面板还存在了这个笔记，怎么才能把它刷新一下

**Comment by Newdea** [comment]
打开卡片面板，或命令行打开一篇笔记复习

**Comment by YIRU69** [comment]
ok。

> 导致这个问题可能是因为 我的这个文本的笔记包含了两种标签，一种是复习标签，一种是卡片标签，我的#review是复习标签，我删除了复习标签，自己的笔记还存在卡片标签，运行`untrack note`命令，就会失效，显示`It is tages file, can't untrack by this. You can delete the #review tag in note file. ` 当我把卡片标签也删除，才成功

这个问题可以修复吗

**Comment by Newdea** [comment]
是指删除笔记复习标签就不显示在右侧面板么，这个必须要刷新下才行（即打开卡片面板或 打开一篇笔记复习）；

还是指删除复习标签，往后就不再复习这篇笔记？这个因和recall的功能合并，相互有些影响，改着可能会比较费事，建议还是手动untrack下吧

还是指要把复习标签和卡片标签全删除，才能手动untrack? 这个可以试着修下，尽量下版 只是删除复习标签就可以手动untrack

**Comment by YIRU69** [comment]
我想要untrack 这个笔记，这个笔记存在复习标签和卡片标签，笔记的卡片还有要复习的，但是笔记就没必要的
所以，我对这个笔记，如果删除复习标签，再 untrack ，它就会不成功，就是这个问题

**Comment by YIRU69** [comment]
另外还反应一个相关的问题，我现在进行同步，数据同步过来，但是插件貌似没有识别到新的数据，没有做更改，只有重启插件，这些更改才能反应到右侧面板，我打开卡片面板或 打开一篇笔记复习并没有刷新成功

**Comment by zxmengde** [comment]
我有类似的问题，具体来说，我无法使用文件选单中的track和untrack来将笔记添加进或移除笔记复习的右侧栏中，只能使用标签的方式标记需要间隔复习的笔记，另外当我删除标签，也无法将笔记移除。
