### ISSUE TITLE
[FEAT] 请问能否增加功能将暂时不想复习的笔记或者卡片延后

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#33]
**Is your feature request related to a problem? 、
进行笔记复习时，遇到需要前置知识的笔记，想把笔记延后复习（2周左右吧）。期间用于学习前置知识的
类似于super memo的[postpone](https://www.yuque.com/supermemo/wiki/postpone)

**Describe the solution you'd like**
能否增加一个"Ctrl-P"能使用的command用于编辑该笔记的开始复习时间，或者延后时间呢

现在使用命令`Spaced Repetition Recall: Item info` 可以查看笔记的复习时间，然后进行手动调节。
感觉有点原始，不优雅的

**Comment by Newdea** [comment]
晚点吧，最近在修提的这几个问题🥲

主分支上好像也有人提这个功能，也许后续直接合过来就好

**Comment by Newdea** [comment]
> 感觉有点原始，不优雅的

这个增加个日期选择器就方便了。

指定延后x天复习，是只用于某篇笔记或笔记内卡片的场景吧，不启用均衡是不是好些

**Comment by Newdea** [comment]
> 这个增加个日期选择器就方便了。

搞不定，哪位可以搭把手

**Comment by dryezl** [comment]
非常感谢，基本可以满足需求的。

**Comment by Newdea** [comment]
> 这个命令需要启用Logging才能看到的。

是的，等后续稳定了再移出来，有问题欢迎及时反馈。

> 延迟某一个卡片
这个实现功能时也考虑过，但感觉没有使用场景，如果一个卡片需要延迟，那这个笔记中的卡片都是相关的，应该也都要延迟的。
其次就是单独延迟一个卡片，程序上有些难以对应实现。
就没有实现了，有那个设置延迟的时间还不如直接复习了事。

另，延迟卡片需求很大么，你目前具体使用场景是怎样的？

**Comment by dryezl** [comment]
因为有一些卡片只设置了问题，没有对应的答案，所以想延迟的。
我先把没有循环的卡片换到另外一个笔记上的。现在这个也是可以的

**Comment by dryezl** [comment]
请问现在延迟动作能不能多增加一步呢？即延迟之后，跳转到下一个复习的笔记的
目前延迟卡片之后仍然停留在该卡片的

**Comment by Newdea** [comment]
所有延迟动作后就打开下一篇，会造成困扰吧，有些不太好。
可以在复习过程中(即复习笔记悬浮栏有打开时)延迟后，如果设置中启用自动下一篇笔记，就打开下一篇笔记，这样如何？

**Comment by dryezl** [comment]
没问题的。有时间，延迟之后，点击右下角的"review: 5 notes",会弹出当前笔记的复习数据，不是进入下一个笔记的

**Comment by Newdea** [comment]
> 有时延迟之后，点击右下角的"review: 5 notes",会弹出当前笔记的复习数据，不是进入下一个笔记的

这可能是当前笔记无法延迟（计算出记忆程度过低（≤0.65）），就不会进行延迟，建议当前就进行复习。


这个问题就先关闭了，如果延迟后不进入下个笔记的问题还在，就提个新问题吧。
