### ISSUE TITLE
[BUG] 版本1.10.5.5 console出现错误

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#34]
新版本中，我发现只要一点开右下角进行复习，调试区就会报错

![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/48148292/62497d33-79d3-4157-9d1e-29f1a2d18d2b)

**Comment by Newdea** [comment]
只是报错，不影响正常复习吧，我这边查下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月3日(周三) 下午3:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [open-spaced-repetition/obsidian-spaced-repetition-recall] [BUG] 版本1.10.5.5 console出现错误 (Issue #34)




 
新版本中，我发现只要一点开右下角进行复习，调试区就会报错
 
image.png (view on web)
