### ISSUE TITLE
[BUG] 1.10.5.5 如果卡片以标签开头的话，卡片被会被按照开头的标签进行分组的

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#35]
插件设置里面卡片复习的标签只有" #fs_all "， 卡片复习的界面发现有其他标签。
查看对应卡片发现 该卡片以标签开头

复现例子如下

```md
#fs_all  (这是卡片复习的标签）

#test
foo
?
bar
```
以上会生成test分组的卡片。理论上来说卡片复习的时候应该只有标明的标签

如果将标签从首行移除，放到其他位置，或者和对应卡片分割开来（空行）。卡片复习的界面的其他标签就会消失的

**Comment by Newdea** [comment]
这个原插件就是这样的，属于正常的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月6日(周六) 中午11:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [open-spaced-repetition/obsidian-spaced-repetition-recall] [BUG] 1.10.5.5 如果卡片以标签开头的话，卡片被会被按照开头的标签进行分组的 (Issue #35)




 
插件设置里面卡片复习的标签只有" #fs_all "， 卡片复习的界面发现有其他标签。
 查看对应卡片发现 该卡片以标签开头
 
复现例子如下
 #fs_all  (这是卡片复习的标签） #test foo ? bar
 
以上会生成test分组的卡片。理论上来说卡片复习的时候应该只有标明的标签
 
如果将标签从首行移除，放到其他位置，或者和对应卡片分割开来（空行）。卡片复习的界面的其他标签就会消失的

**Comment by dryezl** [comment]
好的。这不算bug，算是feature？
那我把这个关了
