### ISSUE TITLE
[FEAT] Keep the project updated with the st3v3nmw/obsidian-spaced-repetition

### ISSUE THREAD

**Issue by MotaOcimar** [open-spaced-repetition/obsidian-spaced-repetition-recall#36]
**Is your feature request related to a problem? Please describe.**
Recently many bugs were fixed and there was a major refactoring involving several improvements to the source code (https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/751).

**Describe the solution you'd like**
I propose updating the current code to keep up with these changes, bringing the fixes and facilitating future development (before the diff become too big 😬😅 )

**Comment by Newdea** [comment]
it has been synchronized with the master branch,  and can be distinguished by the version number

**Comment by MotaOcimar** [comment]
I don't know if I'm missing something, but here shows this project is [20 commits behind st3v3nmw/obsidian-spaced-repetition:master](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/compare/dev-master...st3v3nmw%3Aobsidian-spaced-repetition%3Amaster), what includes the [big one](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/commit/5e8f98859ad9fa62616e00b24758ce9355f58279)

**Comment by Newdea** [comment]
current latest version 1.10.5.5 is up to date with st3v3nmw's master branch 1.10.5 version

**Comment by MotaOcimar** [comment]
Oh, I see now that the merge was done with a [squash commit](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/commit/1dc9f7e0c57f92d9eb53c1db07fb67e422e2184a).

Ok ok. Lgtm

If I can ask, can the next merges be done using some method that preserves the commits tracking?

**Comment by Newdea** [comment]
ok, now it will show the merge status
