### ISSUE TITLE
[BUG]进行复习的时候，没有正确显示今天需要复习的

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#37]
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/48148292/a6dd51a9-d330-4c77-a760-14456c205f5c)
看图上，我今天有要复习的笔记，但是显示是今天要复习的笔记是0

**Comment by Newdea** [comment]
状态栏只是计算截止现在可以复习的，边栏显示的是今天内可以复习的。
比如现在（15:00）可复习是0，但晚上（20:00）会有3篇笔记到期可复习，那状态栏就会显示3

**Comment by YIRU69** [comment]
明白了，我早上的时候没到时间。。
