### ISSUE TITLE
[FEAT]完形填空支持多个空白

### ISSUE THREAD

**Issue by xh542428798** [open-spaced-repetition/obsidian-spaced-repetition-recall#4]
大佬，是否可以解决完形填空只能显示一个空的问题？

**Comment by xh542428798** [comment]
Sir, I found someone else had soved this problem, [aosr](https://github.com/hedyhli/aosr), this plugin based on obsidian-spaced-repetition can recognize tag "#multicloze" to display multicloze, but other functions in that plugin changed a lot, I didn't like it, I really beg you to incorporate "#multicloze" function from aosr, thanks a lot.

**Comment by Newdea** [comment]
这个以后有空再吧，最近时间有限。
或者你fork改下。

**Comment by L-M-Sherlock** [comment]
我没意见，我只管算法相关的。

**Comment by Newdea** [comment]
主分支有人提，但效果不好，就没有合并过来。


如果只是想点哪显示哪，ob中文论坛 有人通过css 方式实现了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月18日(周四) 下午3:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [FEAT]完形填空支持多个空白 (Issue #4)




 
想要multicloze的功能, 然后可以自由猜, 点哪个空翻转哪个空, 效率高些. 在obsidian中用srs一般是围绕笔记开展的, 没有专门弄成问答等形式, 直接全篇内容重点加粗, 然后自由猜, 强化对笔记的记忆, 也减小了记笔记时的摩擦力

**Comment by Newdea** [comment]
目前最新版已经支持了 https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/releases/latest
