### ISSUE TITLE
[BUG] v1.11.0.1 复习记录不能存储在卡片后

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#40]
**Describe the bug**

我原本是选择将卡片复习数据存放到额外的位置的，后来有一些卡片因为行号或内容变动过大，被误认为新卡片。现想把复习记录保存到卡片后面。但是我确认选择
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/47209925/586546ff-f405-4e04-bcfa-d2d4c95fe4c3)
复习后，复习数据不会保存到卡片之后的。

重新建立数据库也有这个问题

**To Reproduce**
note.md
```

#flashcards 


asdfasdf
?
as


lkjlhjlj
?
kjljk



65465465
?
2121


lkjljl
?
54654
```
插件设置 
[data.json](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/files/13944169/data.json)

**Comment by Newdea** [comment]
频繁变动的时候是有这个问题，如果卡片还没做好，可以先跳过，不必复习。


fsrs算法不能保存在笔记上，只有默认算法才可以。
想保存在笔记上，先改为默认算法，再修改DataLocation就可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 上午9:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [open-spaced-repetition/obsidian-spaced-repetition-recall] [BUG] v1.11.0.1 复习记录不能存储在卡片后 (Issue #40)




 
Describe the bug
 
我原本是选择将卡片复习数据存放到额外的位置的，后来有一些卡片因为行号或内容变动过大，被误认为新卡片。现想把复习记录保存到卡片后面。但是我确认选择
 image.png (view on web)
 复习后，复习数据不会保存到卡片之后的。
 
重新建立数据库也有这个问题
 
To Reproduce
 note.md
  #flashcards  asdfasdf ? as lkjlhjlj ? kjljk 65465465 ? 2121 lkjljl ? 54654  
插件设置
 data.json

**Comment by dryezl** [comment]
这样子。请问#20这个还有机会上线吗？如果这个上线的话，是不是也能解决这个卡片变动导致卡片识别出错的问题

**Comment by dryezl** [comment]
这样子。请问#20这个还有机会上线吗？如果这个上线的话，是不是也能解决这个卡片变动导致卡片识别出错的问题

**Comment by Newdea** [comment]
目前没有计划上，那个影响太大，会在所有卡片后增加id。

现在的这种方式已经足够了

**Comment by Newdea** [comment]
FSRS的卡片数据结构比默认算法的复杂些
FSRS
```
export declare class Card {
    due: Date;
    stability: number;
    difficulty: number;
    elapsed_days: number;
    scheduled_days: number;
    reps: number;
    lapses: number;
    state: State;
    last_review: Date;
    constructor();
}
```

默认算法就三个量：
```
sr-due: 2023-12-29
sr-interval: 1
sr-ease: 250
```
