### ISSUE TITLE
[BUG] Bury sibling cards also buries the current card with it (FSRS)

### ISSUE THREAD

**Issue by VerAn1015** [open-spaced-repetition/obsidian-spaced-repetition-recall#45]
Hi. Thanks for incorporating FSRS in this fork. The algorithm is more helpful for me. I could be completely misunderstanding how the plugin works so feel free to close this issue.

**Before report the bug**

-   [x] searched the issues;
-   [x] disable origin `Obsidian Spaced Repetition` plugin;

**Describe the bug**
Turning on setting "Bury sibling cards until the next day?" also buries the current card the next day together with the sibling card in FSRS. 

**To Reproduce**

1. Open Obsidian Sandbox. Install plugin via BRAT. 
2. Set Data Location: In Plugin Folder.
3. Set Algorithm: Fsrs
4. Turn on: Bury sibling cards until the next day?
5. Create sibling cards (inline reversed, multiline reversed, or clozes)
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/148541981/51411688-f0c7-4e99-a608-a640fc1aa388)
6. Review flashcards. Answer Hard - 5 minute(s)
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/148541981/1778d633-c066-4d41-8170-35753715efe9)

**Expected behavior**
Current reviewed card should come back in 5 minutes and not the next day. Only the other sibling card should come back the next day.

**Screenshots**
I'm not well versed in how the developer console works. Sorry

-   [ ] error messages

**Versions (please complete the following information):**

-   [ ] OS: [e.g. iOS]
-   [x] Obsidian version: [e.g. v1.5.3]
-   [x] Plugin version: [e.g. v1.11.1.2]
-   [x] If on desktop, Installer version: [v1.4.16]

**Additional context**

-   Data Location Setting(select):
-   [ ] Save in Note;
-   [x] Save in `tracked_files.json`
-   Algorithm(select):
-   [ ] Default
-   [ ] Anki
-   [x] Fsrs
-   [ ] SM2
-   [ ] Additional context

**Comment by Newdea** [comment]
hi, @VerAn1015 , i have fixed this issue, welcome to use and feedback
