### ISSUE TITLE
[BUG] 无法正常开启卡片复习。

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#50]
首先是报错：
```
plugin:obsidian-spaced-repetition-recall:29516 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'redraw')
    at _SRPlugin.updateAndSortDueNotes (plugin:obsidian-spaced-repetition-recall:29516:28)
    at _SRPlugin.sync (plugin:obsidian-spaced-repetition-recall:29446:10)
    at async eval (plugin:obsidian-spaced-repetition-recall:29331:11)
```
插件的版本是 1.11.1.4 ob 的版本是 1.5.8 

我的操作是：

昨天我自己用了是正常运行的。在公司电脑上用的。然后每次我都要先关闭插件，然而进行同步。

到昨天晚上，自己同步数据，然后家庭电脑上增加了几个笔记。然后同步。其中复习插件没有开启的。

到今天，自己开启公司电脑，同步内容过来。发现自己的复习卡片界面打不开，侧边栏也没有出现。

另外说一个问题。我有时候，某些时候，在同步的时候，必须要重启插件，才能读取到新的数据文件。

**Comment by YIRU69** [comment]
我重启了ob，这个问题就恢复正常了

**Comment by Newdea** [comment]
这个问题是低概率偶发的，之前有尝试修复过，但没有效果。
代码和原插件一致，逻辑是正常的，但不清楚为啥启动插件有时会出这问题。

数据更新的话，如果本设备的数据文件已经更新(判断文件的修改时间)，要手动点击侧边栏的 复习卡片 图标才更新的。

**Comment by YIRU69** [comment]
@Newdea  提交一个新的问题，特别验严重，今天在 ipad 上使用 插件的时候，只要把数据文件保存到制定的位置，ipad 上面的数据就全消失了。。。等于是说这个库都没了

**Comment by Newdea** [comment]
刚注意到你说的这个问题😂，新问题还是开新issue更容易看到。不过没有苹果设备，也不好确定什么原因。
我记得，自定义路径，如果没有点保存，就还是原路径。
如果新路径存在trackfiles.json就会把存在的这个重命名，再移动到目标位置。

希望现在都正常了

> @Newdea 提交一个新的问题，特别验严重，今天在 ipad 上使用 插件的时候，只要把数据文件保存到制定的位置，ipad 上面的数据就全消失了。。。等于是说这个库都没了

**Comment by YIRU69** [comment]
> 希望现在都正常了

我比较少用 ipad 上，偶然尝试了一下同步，没有再进行测试了，毕竟折腾一次比较花精力，谢谢，有问题会反馈，我先关闭问题。
