### ISSUE TITLE
[FEAT] 卡片复习的时候，不要拉伸图片或者增加按钮确认是否拉伸图片的

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#51]
**Is your feature request related to a problem? Please describe.**
复习带有图片的问答卡片时，图片会被拉伸，需要上下移动，才能完整看到图片的。
有些图片清晰度不够的，很小被拉伸大之后，马赛克效果比较严重的
图片在笔记中渲染是没有问题的，正常大小的。
目前复习卡片窗口拉伸图片，好像是保持纵横比，拉伸图片的宽度和窗口宽度一致的

如果我在缩小复习窗口相对obsidian的宽度话，部分图片（比较小的）可能显示效果会好一些
**Describe the solution you'd like**
复习窗口渲染图片时，不拉伸图片。或者在设置中增加按钮确认是否拉伸图片

**Comment by Newdea** [comment]
这部分和原插件一样，精力有限，如果确实需要，就在上游仓库提下issue吧
