### ISSUE TITLE
[BUG] 笔记复习选择记得（1天），下次复习日期并没有改变。

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#53]
对于新笔记，按照 FSRS 算法，首先选择较难，下次推送时「记得」的间隔是1天。但是在选择「记得」后，下次的复习日期反而是点击「记得」按钮时的当下时间。
有意思的是当这个笔记再推送给我时「记得」的间隔是2天，而选择「记得」后，实际的到期天数是三天后。

**Comment by Newdea** [comment]
是通过 iteminfo查看的么，时间一样，但日期应该不同吧，我这边使用一直正常，方便提供下具体的数据或截图么。

**Comment by tangwells** [comment]
是的查看 iteminfo 的 nextReview。
<img width="543" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/04903337-0a3b-44cb-bb20-177da241bf3e">
<img width="542" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/ac7a1c75-a306-4dee-bb1f-0d11038bf246">
<img width="544" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/97d1a32d-a5d6-4b18-b7b9-31487f117862">

**Comment by Newdea** [comment]
> 第二次选记得后，时间直接刷新为当下。

多谢反馈，这个刚才我手机上也复现出来了，下版修复

> 或者说那个悬浮栏的间隔时间是错误的，让我产生了误解？但确实出现了刚选择记得的笔记下一秒又直接推送给我了。

下次复习时间是当天的话，可能就也能直接复习了，这块有尝试改过，但时灵时不灵的（有些版本是ok的更新几版后又出问题）。。。。。

> 当这个笔记再推送给我时「记得」的间隔是2天，而选择「记得」后，实际的到期天数是三天后。

这个应该是均衡起作用的，可能2天后的复习笔记数过多，就会调整到三天后。

**Comment by Newdea** [comment]
今天晚上在电脑（win11）上试很久，没有复现。而且查了我手机下午操作的截图，也是正常的（时间是现在，但日期是三天后了）。你能按照问题模板详细提供下信息么，没法复现的话，这个问题不容易定位。

**Comment by tangwells** [comment]
**Before report the bug**

-   [ ] searched the issues;
-   [X] disable origin `Obsidian Sapced Repetition` plugin;

**Describe the bug**
对于一篇新笔记，第一次选择“重来“，理论间隔时间为1min，实际间隔时间为5min；第二次选择“记得“，理论间隔时间为1day，实际间隔时间为0.

**To Reproduce**
1. 新建一个空仓库，安装本插件。
2. 新建一篇笔记，设置#review标签，开始回顾。
3. 第一次选择重来，理论间隔时间为1min。
4. 第二次选择记得，理论间隔时间为1day。
5. 这个 bug 具有偶发性。也许与我的#review标签下还有子标签有关，又或者我的时间戳命名有关？

**Expected behavior**
第二次选择记得后，实际间隔时间应为1day。

**Screenshots**
[IMG_2770.mov.zip](https://github.com/user-attachments/files/15718939/IMG_2770.mov.zip)
这个是从一段尝试中截取的出现 bug 的一段。按照以上复现步骤，大概1/6的频率吧。

**Versions (please complete the following information):**

-   [X] macOS
-   [X] Obsidian version: [e.g. v1.5.12]
-   [X] Plugin version: [e.g. v1.11.1.4]

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

-   Data Location Setting(select):
-   [ ] Save in Note;
-   [X] Save in `tracked_files.json`
-   Algorithm(select):
-   [ ] Default
-   [ ] Anki
-   [X] Fsrs
-   [ ] SM2
-   [ ] Additional context

**Comment by tangwells** [comment]
<img width="544" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/34f4c533-ef70-4953-8b55-b9a952c54a19">
不知道这个截图是否也能反映一点问题，这个也是一个出现 bug 的笔记，其中 NextReview 与 Due 的时间正好差了一天。而正常的笔记中，NextReview 与 Due是一致的。

**Comment by tangwells** [comment]
omg，我不小心关闭这个 bug 反馈了

**Comment by tangwells** [comment]
hello，我发现我的插件文件夹里有个叫tracked_files.json.Default.bak的文件，这个是必要的吗？

**Comment by tangwells** [comment]
报错信息及控制台情况如下：
<img width="1162" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/c0fc3e9a-3681-4c84-9866-bbb0d4aaf669">
<img width="1241" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/ff10683d-3150-4c5b-b170-8c9c7e05dff2">

**Comment by Newdea** [comment]
这个问题应该是自动均衡导致的，我改了一版，你试用反馈下，没问题我下版发布时就合并进去。
[main_fixedNextReview.zip](https://github.com/user-attachments/files/15887506/main_fixedNextReview.zip)




> tracked_files.json.Default.bak的文件，这个是必要的吗

这个是算法切换时的备份文件，如果切换后没有出问题可以删除。

**Comment by tangwells** [comment]
好的大佬，我这就试试

**Comment by tangwells** [comment]
大佬，在阅读视图下，将鼠标放置在悬浮框的某个选项上，然后使用快捷键1、2、3来选择间隔时间后，就出现了自动浮现item info 的窗口。重启后即便是打开一篇新笔记也会复现。
[IMG_2786.MOV.zip](https://github.com/user-attachments/files/15894834/IMG_2786.MOV.zip)

**Comment by tangwells** [comment]
> 重启后即便是打开一篇新笔记也会复现。
在设置界面，将插件停止使用后，再重启 ob 后，该 bug 不再出现。

**Comment by Newdea** [comment]
可能是排序出问题了，之前出现过，试下这个命令
clear queue





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月19日(周三) 中午11:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [BUG] 笔记复习选择记得（1天），下次复习日期并没有改变。 (Issue #53)




  
重启后即便是打开一篇新笔记也会复现。
  
在设置界面，将插件停止使用后，再重启 ob 后，该 bug 不再出现。

**Comment by Newdea** [comment]
这个issue只讨论 复习日期没有更新的问题吧，免得弄混。
