### ISSUE TITLE
[bug]复习时打开了还没到复习时间的笔记

### ISSUE THREAD

**Issue by Newdea** [open-spaced-repetition/obsidian-spaced-repetition-recall#54]
而更奇葩的是，即便我用 release 里1.11.1.4版本的 main.js，替换掉你给我发的那个版本依然会出现这个问题：打开一篇笔记开始复习，自动浮现 item info，同时一直打开的是一篇应当在未来推送给我的笔记：
<img width="557" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/6a8a565d-f3a3-4247-9776-5381c79ac2ce">

_Originally posted by @tangwells in https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/53#issuecomment-2177463504_

**Comment by Newdea** [comment]
@tangwells 需要设置里打开 调试记录，然后重启OB，应该就有这个命令了
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/af8e112b-db8c-49df-b9e6-39ebed03f47e)


![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/34621333-07fa-4b01-8342-22516c91bfa2)

**Comment by Newdea** [comment]
如果方便的话，先不要执行上面命令，在再次出现这个问题时，先截图下控制台的调试信息
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/3b9ab083-246c-4a1f-8e95-2c4705c85a4f)

前段时间就想解决这个问题，但一直没有复现，找不到原因。

**Comment by tangwells** [comment]
好的，我会留意

**Comment by tangwells** [comment]
这个问题由于那篇笔记我之前直接踢出复习队列了，就没再复现。如果再有出现我再反馈吧。
