### ISSUE TITLE
[Bug]: 复习笔记时，直接推送了没有到期的笔记

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#56]
### Describe the bug

对于一篇笔记，如果选择重来（5m），并不会自动打开下一篇笔记，而是一直呈现这篇笔记。但在 item info 中，其下一次复习时间确实是5m 后。实际操作发现，除了选择5m 的间隔，10m 的间隔也会触发这一问题。
对应的控制台信息如下：
<img width="723" alt="image" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/fafafdb7-6996-4cf4-aa6b-901d0866870d">
全屏信息展示：
<img width="1440" alt="Pasted Graphic 2" src="https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/132054668/0fc6798e-36c0-499e-9ab6-58661b84f597">

### To Reproduce

1. 随意打开一篇今日待复习笔记。
2. 选择重来按钮。

### Expected behavior

选择重来（5m），应在5m 后再复习该笔记

### OS of your device

mac os sonoma 14.5

### Obsidian version

v1.6.3

### Plugin version

v1.12.4.5

**Comment by tangwells** [comment]
使用你原先发给我的那个测试用的 main.js，该 bug 没有出现

**Comment by tangwells** [comment]
大佬，悬浮栏的不是什么大问题，重点是这个 bug。我新建了一个仓库来进行测试，发现当前插件逻辑是：
- 当打开一篇笔记开始复习时，它会优先推送今天待复习笔记中，nextreviewtime 距离当下最近的一篇笔记，即便这篇笔记是我选择重来的笔记。
- 由于我选择重来的笔记的间隔时间是5m，因此当插件要推送给我下一篇笔记时，遍历整个牌组发现这个间隔5m 的笔记是距离当下最近的笔记，因此就把这个笔记又直接推送给我了。

**Comment by Newdea** [comment]
嗯，在查了，先用之前那版吧

**Comment by Newdea** [comment]
现在这版（1.12.4.6）修复了，我电脑上已经可以只在到期时推送了，你再试下。

**Comment by tangwells** [comment]
目前没有这个问题了，我先 cloze了。

**Comment by tangwells** [comment]
> 消失前的我的最后一个具体操作是：在阅读模式下，使用快捷键“0”来对笔记选择重来。

现在看来与这个操作似乎没有直接关系，因为就在刚刚，这个bug 它又复现了。复现的场景是，某篇笔记选择了今天重来，再推送给我时「记得」的间隔为1天，我在选择记得后就开始每篇笔记都自动弹出 item info 窗口了。控制台的信息与我先前发送的是一致的。我再观察一下，如果还是出现这个问题我再给你发送笔记库。

**Comment by tangwells** [comment]
[bug 库.zip](https://github.com/user-attachments/files/15963597/bug.zip)
这是我的笔记库，个人及重要信息都已删除，插件啥的打开即用。上传前已确认还是会自动弹出 item info 窗口的。

**Comment by Newdea** [comment]
用你这个复现了几次弹item info窗口，看了复习数据，是可以复习，并不算是提前。

正常推送的逻辑 ：
1. 上次复习时间是当天之前，nextReview是当天之内；或
2. 上次复习时间是当天，nextReview在现在时间之前。

弹item info 窗口的判断条件不全导致的，已经修改了，试过没有再出现，你再试下。效果如何请反馈下。
[main_fix.zip](https://github.com/user-attachments/files/15972171/main_fix.zip)

**Comment by tangwells** [comment]
自动弹出 item info 窗口的问题解决了！
