### ISSUE TITLE
[Bug]: Review Buttons only shows "hard" and are not clickable (Windows 10 and iPadOS 17.5.1)

### ISSUE THREAD

**Issue by JDrasko** [open-spaced-repetition/obsidian-spaced-repetition-recall#60]
### Describe the bug

When reviewing my flashcards after showing the answer i cant categorize them to "easy", "good" or "hard". 
All buttons shows "hard" and are not clickable.

### To Reproduce

1. Create Flashcard with :: (inline) or ? (Multiline)
2. Review flashcards.
3. Show answer.
4. Categorization bugs.

### Expected behavior

Button should show "Easy", "Good", and "Hard" and should be clickable.

### Screenshots

This is my note:
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/131792420/1580c8c2-ed19-432c-ae75-b88d265e75c1)

This is the review window:
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/131792420/b26d6fbc-1d62-4064-8937-b5c51a9bd73b)

And here the logs of developer console:
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/131792420/2ee0bd1f-6597-40e9-8280-7b5625b8a8eb)

### OS of your device

Win10, iPadOS 17.5.1 (iPad Pro 12,9" 6.Gen)

### Obsidian version

v1.6.3

### Plugin version

v1.12.4.6

### Installer version

v1.4.16

### Config file

[data.json](https://github.com/user-attachments/files/15966731/data.json)
[2024-06-25.md](https://github.com/user-attachments/files/15966733/2024-06-25.md)

**Comment by JDrasko** [comment]
When i change Data Location to "In Vault Folder" it seem to work again.

![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/131792420/515138d0-d3d7-4d64-b8b6-78c3fc853468)

**Comment by Newdea** [comment]
ok, if it appears again, please reoen/pull issue, any feedback is welcome~
