### ISSUE TITLE
[FEAT]: 新笔记组的笔记复习最好优先推送最早添加的笔记

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#63]
### Describe the solution you'd like

学习过程是渐进的，从简到难的过程。目前的新笔记推送逻辑是先推送最新添加的笔记，这导致比较难的知识被更早地推送给学习者。
希望新笔记组的推送顺序能进行更改：将最早添加的笔记进行优先推送。

**Comment by Newdea** [comment]
目前好像是这样的，我有空试着改下吧。

临时方案，可以开随机
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/962bf5c2-e0ca-445f-a764-9404462b7b3d)

**Comment by tangwells** [comment]
大佬，我真的哭死了。您太伟大了！

**Comment by tangwells** [comment]
大佬您好，经过2～3天的高强度使用，就笔记复习上并没有遇上任何 bug，使用体验上非常完美。由于我没有使用卡片复习的功能所以就卡片复习上是否可能有其他问题得看其他用户的使用情况了。

**Comment by Newdea** [comment]
已经加入到新版本内了

**Comment by tangwells** [comment]
大佬新版本中新笔记的推送顺序似乎还是按照原来的排序进行推送的，并不是按照笔记创建的先后顺序。详见下图：
<img width="186" alt="image" src="https://github.com/user-attachments/assets/7d0c58fe-ef73-43f6-be4e-2e1547aa55bf">
