### ISSUE TITLE
[feat]blockid自定义生成规则

### ISSUE THREAD

**Issue by Newdea** [open-spaced-repetition/obsidian-spaced-repetition-recall#64]
增加前缀+时间，比如 数学笔记 `^math-2024070208572399` 这个格式 前缀加时间格式 `YYYYMMDDHHmmssSS` 或者有其他

_Originally posted by @YIRU69 in https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/20#issuecomment-2226870321_

**Comment by Newdea** [comment]
@YIRU69 这个`math` 是文件名中，还是tag标签的，生成时从哪里提取到它呢

**Comment by Newdea** [comment]
另，目前你手动修改已经生成的blockid，只要不改卡片的行号和内容，也是可以保证卡片信息还能对上的。

**Comment by YIRU69** [comment]
只是为了方便追踪和引用， math 就是 blockid 的名字呀



> 另，目前你手动修改已经生成的blockid，只要不改卡片的行号和内容，也是可以保证卡片信息还能对上的。

如果我改变了卡片的行号和内容，是否意味着又要重新复习，这个卡片变成了新卡片呀？

如果是这样的话，那么增加 blockid 的本来的意义好像失去了，增加 blockid 的意义就是为了可以更改卡片的行号和内容，而且不会影响同文档的下面的卡片（如果更改了中间的卡片，比如增加了很多内容，那么下面的卡片的行数就会改变，会导致下面的卡片变成新的卡片，丢失复习记录）

**Comment by Newdea** [comment]
不是的，只是说你手动改Blokid时，别改内容。
具体效果你试下就清楚了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 上午8:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [feat]blockid自定义生成规则 (Issue #64)




 
只是为了方便追踪和引用， math 就是 blockid 的名字呀
  
另，目前你手动修改已经生成的blockid，只要不改卡片的行号和内容，也是可以保证卡片信息还能对上的。
  
如果我改变了卡片的行号和内容，是否意味着又要重新复习，这个卡片变成了新卡片呀？
 
如果是这样的话，那么增加 blockid 的本来的意义好像失去了，增加 blockid 的意义就是为了可以更改卡片的行号和内容，而且不会影响同文档的下面的卡片（如果更改了中间的卡片，比如增加了很多内容，那么下面的卡片的行数就会改变，会导致下面的卡片变成新的卡片，丢失复习记录）

**Comment by YIRU69** [comment]
谢谢，我可能理解错了，我更改行号和内容还是能正常复习，没有造成出现额外的新卡片

**Comment by Newdea** [comment]
> 只是为了方便追踪和引用， math 就是 blockid 的名字呀

比如说，你这复习卡片有多个文件，有些文件内的卡片并不是数学相关，blockid还是用`math`么，不应该这样吧。所以才问你 生成blockid时从哪里提取到它？

不知是否理解我的问题

一种规则是可以用该文件中的tag作前缀，然后跟生成时的时间戳（如`^flashcard-202407162112460000`）。
但这样有个问题，就是会产生大量这种信息，在搜索时，可能会污染搜索结果。而且本身也算是在污染文本了。
当然，也许不使用这种日期搜索的可能感受不到。我自己日常使用，是习惯用时间戳的，搜索时，是不希望有这么多自动生成的无意义时间戳。

那另外就是tag作前缀，然后跟随机字母数字，即类似当前的。如`flashcard-hwzav3`

当然，加这种前缀，也容易造成文本污染。

不知你有什么看法。

**Comment by YIRU69** [comment]
tag 有多个，所以在生成上就有问题

> 你这复习卡片有多个文件，有些文件内的卡片并不是数学相关

你说的确实是问题，我考虑不周全，这个功能如果按照标签好像也存在问题，比如我的标签中有表情符号，也不方便添加

> 一种规则是可以用该文件中的tag作前缀，然后跟生成时的时间戳 

这种我觉得除了标签可以换个固定的，比如你说的 `^flashcard-202407162112460000` 

思考下来，这个问题的优先级好像不高，主要是为了想要做一些统计和引用上方便

**Comment by Newdea** [comment]
嗯，这个确实没有什么必要。
在实际引用时输入正文内容，Obsidian就自动完成，如果要手动输入blockid，自然是简短些更好。

这个问题就先关闭了。
