### ISSUE TITLE
新笔记的推送逻辑

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#66]
已经加入到新版本内了

_Originally posted by @Newdea in https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/63#issuecomment-2241531934_
 
大佬，新版本中新笔记的推送似乎不是按照笔记创建的先后顺序进行排序的，可见下图：
<img width="186" alt="image" src="https://github.com/user-attachments/assets/bd15d72f-3f17-4ee5-a8d1-f9b35fe26642">
在使用中，确实直接推送给我了一个最新创建的笔记。

**Comment by Newdea** [comment]
不完全是按创建时间，先是按重要度（pragrank），然后才是创建时间。这是源代码
```ts
&nbsp; sortNotes(pageranks) {
&nbsp; &nbsp; this.newNotes = this.newNotes.sort((a, b) =&gt; {
&nbsp; &nbsp; &nbsp; const result = (pageranks[b.note.path] || 0) - (pageranks[a.note.path] || 0);
&nbsp; &nbsp; &nbsp; if (result != 0) {
&nbsp; &nbsp; &nbsp; &nbsp; return result;
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; return a.note.stat.ctime - b.note.stat.ctime;
&nbsp; &nbsp; });

```





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 上午10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [open-spaced-repetition/obsidian-spaced-repetition-recall] 新笔记的推送逻辑 (Issue #66)




           已经加入到新版本内了  
Originally posted by @Newdea in #63 (comment)
 
大佬，新版本中新笔记的推送似乎不是按照笔记创建的先后顺序进行排序的，可见下图：
 
 在使用中，确实直接推送给我了一个最新创建的笔记。

**Comment by tangwells** [comment]
好的，明白了，谢谢

**Comment by tangwells** [comment]
呜呜呜，大佬，请问是否可以对于新笔记还是只按照创建时间的先后顺序来呀。对于我而言，新笔记池里堆积了300个新笔记，它们实际并不能保证先进先出。实际情况如下：
<img width="191" alt="image" src="https://github.com/user-attachments/assets/4536a950-7699-4312-926b-319aa35faada">
如您所见，很多最近添加的笔记的优先级要大于很早之前的笔记，而这个问题如果遍历整个新笔记池会发现及其严重。这使得对循序渐进的知识摄取造成了极大困扰。我很难正常地规划我的学习进程。
再次拜托大佬，可否将新笔记的推送逻辑还是改成按照创建时间先后的先进先出呢！拜托您了！

**Comment by Newdea** [comment]
那就新笔记只按文件创建时间排序，不再根据pagerank重要度了。

[main_fixNewnotesSort.zip](https://github.com/user-attachments/files/16505435/main_fixNewnotesSort.zip)

**Comment by tangwells** [comment]
感谢大佬，大佬万岁！
