### ISSUE TITLE
[Bug]: 混合复习模式下，今日待复习笔记未到期时，不推送新笔记

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#67]
### Describe the bug

在混合复习模式下，如果今日待复习笔记基本复习完毕，剩余1～2个今日笔记都是须几分钟后再复习的时候，不会自动推送新笔记进行复习。
<img width="770" alt="image" src="https://github.com/user-attachments/assets/15a0ff63-5e99-4779-9eda-aa6f45cc4734">
<img width="299" alt="image" src="https://github.com/user-attachments/assets/3193128d-c9c7-40b8-bd06-5265a614dec7">

### To Reproduce

1. 新笔记队列里存在笔记
2. 今日待复习笔记只有几个，且待复习时间都在几分钟后。
3. 选择打开一篇笔记进行复习功能

### Expected behavior

希望能在当前情况下能正常推送新笔记，或者退出混合复习模式？

### OS of your device

mac os sonoma 14.5

### Obsidian version

v1.6.7

### Plugin version

最新版本

**Comment by Newdea** [comment]
1. 如果待复习笔记是当天已经复习过的，必须时间到了才能复习。这个与混合序列无关。
2. 如果不想用混合序列，可以调节第二个滑条，值等于第一个滑条值为优先复习到期的（即之前版本的），值等于零为优先复习新笔记

> 希望能在当前情况下能正常推送新笔记

没明白你的意思，新笔记是有推送的。还是说就是指退出混合序列，像之前版本的到期优先？

**Comment by Newdea** [comment]
另外，这个设置后要重启插件或ob才生效，我下版改成立即生效吧。

**Comment by tangwells** [comment]
这里先定义一下：
- 临期笔记：指重来的旧笔记与正在学习的新笔记，它们的到期时间都在某时刻（当下）的几分钟后。

如视频所见，当今日待复习笔记队列中只存在「临期笔记」或者没有笔记时，插件并不会推送新笔记而是提示“复习完毕，明日再来“。个人认为这是由于新版本的 mix queue 功能所导致的bug。
（这个功能实际上个人十分喜欢，大大提高了每日新笔记学习的进度。）

至于前面所提到的：
>希望能在当前情况下能正常推送新笔记

实际只是希望当今日待复习笔记队列中只存在「临期笔记」或者没有笔记时，在不需要再对 mix queue 功能进行设置调整的情况下，能正常地推送新笔记。

**Comment by tangwells** [comment]
emmm，大佬 这个问题似乎不会非常稳定的发生，但确实存在。现在新笔记又可以正常被推送及学习了。

**Comment by Newdea** [comment]
找到原因了，是到期笔记数还没达到就没有到期笔记时，就会出现这个问题，已经修改了，你试下

[main_fixMixQue.zip](https://github.com/user-attachments/files/16333521/main_fixMixQue.zip)

**Comment by tangwells** [comment]
报告大佬，经过2天对于笔记复习模块的高强度使用，所反馈的问题未再发生。

**Comment by Newdea** [comment]
多谢反馈，下版合进去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月26日(周五) 上午9:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [Bug]: 混合复习模式下，今日待复习笔记未到期时，不推送新笔记 (Issue #67)




 
报告大佬，经过2天对于笔记复习模块的高强度使用，所反馈的问题未再发生。
