### ISSUE TITLE
[FEAT]希望重新添加上“打开文件”这个功能

### ISSUE THREAD

**Issue by YIRU69** [open-spaced-repetition/obsidian-spaced-repetition-recall#7]
你好，很感激你能维护这个插件，原作者很长时间没有维护插件了，而且还加入了新的算法，真的很感激你

刚使用发现必须重启才能正常工作，不然有一点bug

我希望加一个原来原插件除去的功能，看原插件上也有人有这样的需求

[[FEAT] It have been better if you didn't delete the "Open file" feature because](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/661)

希望重新添加上“打开文件”这个功能，谢谢

**Comment by YIRU69** [comment]
在使用过程中，发现如果在复习笔记的时候，悬浮框里面可以添加复习的信息，比如上次的复习时间和复习的次数之类的

**Comment by Newdea** [comment]
卡片复习，有编辑功能就够了吧，感觉没必要再打开文件

**Comment by Newdea** [comment]
> 在使用过程中，发现如果在复习笔记的时候，悬浮框里面可以添加复习的信息，比如上次的复习时间和复习的次数之类的

这个也没太大必要，能知道下次多久会再复习道就可以，咋还要知道前一次的信息呢，显示的多了容易数字焦虑。
那些会有日志文件记录每次的复习情况（用fsrs算法时）

**Comment by YIRU69** [comment]
> 卡片复习，有编辑功能就够了吧，感觉没必要再打开文件

编辑功能只是定位到卡片的部分，而且比较不方便，如果定位到文件修改会更舒服一些

复习的一些信息在日志文件很难查看，而且貌似我记得是没有复习次数吧，至于数字焦虑这个没可能吧，不喜欢可以关掉就好了，我是想 Supermemo 上面是有这个卡片信息的，这样就能更好的知道你回答这个卡片的历史趋势，来分析这个卡片的知识点的掌握程度

**Comment by YIRU69** [comment]
好的，谢谢

**Comment by YIRU69** [comment]
@Newdea 请问一下，如果我移动了笔记，那么这个笔记的复习进度还在，还是要重新构建？或者给这个笔记重命名

**Comment by Newdea** [comment]
> 

在Obsidian软件内移动、重命名的话，进度就还在。
否则，就会按新的处理。

**Comment by Newdea** [comment]
打开文件这个功能，已经加上，更新最新版1.10.1.7就可以用。

但这种方式感觉有些不自然，你用得惯么

**Comment by YIRU69** [comment]
很好，非常感谢！！！

**Comment by YIRU69** [comment]
> 打开文件这个功能，已经加上，更新最新版1.10.1.7就可以用。
> 
> 但这种方式感觉有些不自然，你用得惯么

不是很频繁的用，但是在进行卡片改动编辑的时候，比用小框要好，直接在原笔记里进行书写好多了

**Comment by YIRU69** [comment]
另外提一下，你的赞赏的图在 readme 上面好像有点小<.>

**Comment by Newdea** [comment]
好的，多谢提醒😅
