### ISSUE TITLE
[Bug]: Cards not showing

### ISSUE THREAD

**Issue by mufflemonster** [open-spaced-repetition/obsidian-spaced-repetition-recall#71]
### Describe the bug

First time is ok. 
![Obsidian_Gld2JQ08Tv](https://github.com/user-attachments/assets/d8e6c589-bfb3-445d-a2cd-156461873ab6)
But on the next days cards not showing.
![Obsidian_k25xQ9ob70](https://github.com/user-attachments/assets/09c0532a-4d2a-430b-9916-ed333a27fcf5)
![Obsidian_v0qTEbHw67](https://github.com/user-attachments/assets/b6b34dfd-16d2-4c1b-9356-c5f8f6173119)
I can skip them until they start showing. Like either card is doubling for working and not working card.

### To Reproduce

1. Create card with ?
2. First time card showing. 
3. On the next days card is stop showing

### Expected behavior

Showing cards...

### OS of your device

win 10

### Obsidian version

1.6.7.

### Plugin version

1.12.5

**Comment by Newdea** [comment]
hi, it seems like you are using the original [st plugin](https://github.com/st3v3nmw/obsidian-spaced-repetition), which is my plugin forked from.

**Comment by mufflemonster** [comment]
> hi, it seems like you are using the original [st plugin](https://github.com/st3v3nmw/obsidian-spaced-repetition), which is my plugin forked from.
> 
> you should open issue at https://github.com/st3v3nmw/obsidian-spaced-repetition/issues

oh sorry, thanks!
