### ISSUE TITLE
[Bug]: Plugin is incompatible with Excalidraw files

### ISSUE THREAD

**Issue by JoeKays** [open-spaced-repetition/obsidian-spaced-repetition-recall#72]
### Describe the bug

Hi, when using the 'Convert folders to decks and subdecks' option and 'Highlight clozes' is enabled, there is the problem that Excalidraw files are mistakenly interpreted as flashcards (see screenshots).
This is because all Excalidraw files begin with the following highlighted line:
==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠==
Thanks!

### To Reproduce

1. Enable Convert folders to decks and subdecks
2. Create an empty Excalidraw file in the folder
3. Review deck

### Expected behavior

Excalidraw files are not shown as cards, but completely excluded from review.

### Screenshots

![grafik](https://github.com/user-attachments/assets/b5b3f891-5a96-427c-8985-3cbf4520b522)
---
![grafik](https://github.com/user-attachments/assets/e4a24722-4bd1-4af5-9115-515ed1451214)

### OS of your device

Windows 11

### Obsidian version

v1.6.7

### Plugin version

v1.12.4.9

**Comment by JoeKays** [comment]
@Newdea Unfortunately no, I have Excalidraw files in most of my folders. Therefore, I'd need an exclude filter for either files with .excalidraw extension or with #excalidraw tag.

**Comment by Newdea** [comment]
i see, maybe you can disable convert higlight to clozes.&nbsp;
Or dont use convert folder to decks, just add review flashcards&nbsp; tag to notes.
Just curious, Why do you want to convert all notes to decks, whats your usecase?





---Original---
From: ***@***.***&gt;
Date: Wed, Aug 28, 2024 04:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [Bug]:Plugin is incompatible with Excalidraw files (Issue #72)




 
@Newdea Unfortunately no, I have Excalidraw files in most of my folders. Therefore, I'd need an exclude filter for either files with .excalidraw extension or with #excalidraw tag.

**Comment by JoeKays** [comment]
Well, that'd be a workaround but hardly solves the problem. I have several subjects with different topics that I want to study and I have my drawings in Excalidraw next to my notes. Thus it makes sense to have all flashcards about one topic as notes inside the topic's folder. Having to tag every single note individually would be possible but I don't see why this should be necessary. It has the disadvantage that one could easily forget to tag a note and thus forget about the flashcards in the note entirely.
Since it's already possible to include notes by tag, why not also exclude them by tag (in this case #excalidraw)?

**Comment by Newdea** [comment]
Thanks for you feedback, i come up another way may solve your question.
If your excalidraw filenames all startwith `Drawing` and/or endwith `.excalidraw.md`, add them to ignored folders would also work. But it may ignore your normal files which has same prefix or suffix filename.

**Comment by Newdea** [comment]
![Uploading Screenshot_2024-08-29-09-31-12-778_md.obsidian-edit.jpg…]()

**Comment by Newdea** [comment]
BTW, I will add setting of ignore tag the next version

**Comment by JoeKays** [comment]
> If your excalidraw filenames all startwith `Drawing` and/or endwith `.excalidraw.md`, add them to ignored folders would also work. But it may ignore your normal files which has same prefix or suffix filename.

Thanks, that's actually a good workaround in the meantime, I didn't know that was possible, thank you!

Thanks also for considering the tag ignore for the next version, looking forward to it!
