### ISSUE TITLE
[Bug]: problem with setting w parameter for fsrs 

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#73]
### Describe the bug

I use fsrs-optimizer to optimize parameter based on my review records. The following is part of output of fsrs-optimizer. When I pasted the w parameter into the setting, obsidian echo "Please provide a valid number", change the w parameter into default.

```html
Paste this into your scheduling code
{
    // Generated, Optimized anki deck settings
    "deckName": "ob_revlog",// PLEASE CHANGE THIS TO THE DECKS PROPER NAME
    "w": [1.2322, 3.2059, 13.5946, 31.6453, 7.2258, 0.5407, 0.9276, 0.0186, 1.6288, 0.1897, 1.1254, 2.064, 0.0102, 0.3664, 2.764, 0.0527, 3.0508, 0.343, 0.1414],
    "requestRetention": 0.83465713201,
    "maximumInterval": 36500,
},
```

### To Reproduce

paste the w parameter into plugin setting

### Expected behavior

setting new w parameter

### OS of your device

Win 10

### Obsidian version

1.5.8

### Plugin version

1.12.4.9

**Comment by Newdea** [comment]
只复制w的参数就行：`1.2322, 3.2059, 13.5946, 31.6453, 7.2258, 0.5407, 0.9276, 0.0186, 1.6288, 0.1897, 1.1254, 2.064, 0.0102, 0.3664, 2.764, 0.0527, 3.0508, 0.343, 0.1414`
但是优化器是fsrs v5版（19个参数，不太确定是不是v5版，麻烦@L-M-Sherlock 确定下），插件目前使用的是fsrs v4.5版（17个参数）。
@L-M-Sherlock 请问，能否把优化后的参数，删除两个，在fsrs v4.5使用呢

**Comment by dryezl** [comment]
fsrs-optimizer的具体版本是5.0.6 
```html
Successfully installed fsrs-optimizer-5.0.6 
```

**Comment by L-M-Sherlock** [comment]
上策：升级到 v5
中策：用 v4 的优化器
下策：把 v5 的参数最后两个去掉

**Comment by Newdea** [comment]
那就下版把插件升级下，支持fsrs v5版
