### ISSUE TITLE
[Bug]: 复习队列中，新笔记列表无法弹开

### ISSUE THREAD

**Issue by tangwells** [open-spaced-repetition/obsidian-spaced-repetition-recall#76]
### Describe the bug

更新最新版本后，复习队列的新笔记列表无法正常弹开，除非目前正好推送了一篇新笔记。
<img width="245" alt="image" src="https://github.com/user-attachments/assets/72e2e6a9-5953-4f45-a76e-4280c9c240a2">
以及请问能否在队列的天（新笔记、今天、明天）后面增加一个当天待复习笔记数量的标识，我在实际使用中发现
<img width="177" alt="image" src="https://github.com/user-attachments/assets/d42a1f9f-06d0-4ba7-9418-91eeb7d1cf27">
这个看板反映的当天待复习数据似乎并不准确，它似乎是根据当下时间之前有多少笔记到期来进行计算的，而不是当日有多少笔记到期。

### To Reproduce

启动笔记复习队列窗口，点开新笔记列表。

### Expected behavior

1. 新笔记列表能够正常弹开。
2. 笔记复习对列窗口中，每个日期后面能显示当天的待复习笔记数量。

### OS of your device

mac os sonoma 14.5

### Obsidian version

v1.6.7

### Plugin version

最新版本

**Comment by Newdea** [comment]
[main_fixSidebarNoteDisplay.zip](https://github.com/user-attachments/files/16838931/main_fixSidebarNoteDisplay.zip)

侧边栏没显示笔记的问题，原插件也有这个问题，之前应该是一直有的，可能最近不怎么使用侧边栏，就没关注到。感谢反馈。

2. 状态栏笔记数量这个，之前有讨论过 https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/37#issuecomment-1888558462
