### ISSUE TITLE
[Bug]: flash card render error

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#77]
### Describe the bug

1. flash card with empty line in blocks would be rendered with only a small part of it
2. content in code chunk will render as cloze (double equator used for judgement rather than clozes)

#### example for first question

````

this is a test
```txt
---
for yaml
---
code here ?

fooo bar
foo bar
---
```
?
`layout: true`
````

#### example for second question   

````
```txt 
a = b == "test" & c == "test"
```
````

### Expected behavior

code chunk should be included as a whole.

### OS of your device

Win 10

### Obsidian version

1.5.8

### Plugin version

1.12.5.10

**Comment by Newdea** [comment]
hi, it's a bit werid, can you upload the original md file and data.json file.

```
> `layout: true`
> ```
```
the ``` looks redundant

**Comment by dryezl** [comment]
[example for first question.md](https://github.com/user-attachments/files/16841875/example.for.first.question.md)
[example for second question.md](https://github.com/user-attachments/files/16841876/example.for.second.question.md)
[data.json](https://github.com/user-attachments/files/16841882/data.json)

The above are the corresponding files for examples and data.json. 
I am sorry for the misspell in the first comment and  have revised it accordingly.

**Comment by Newdea** [comment]
hi, since this version has sync upsteam branch which use peggy package to parse cardtext,    it's very different from before. So it will take some time and energy to fix this bug, If it disturbs you, you can rollback to previous version.
BR

**Comment by dryezl** [comment]
Thank you for your time and attention. Looking forward to the newer verison with bug fixxed. 

I will use the previous version, and update it with fsrs v5.  

https://github.com/dryezl/obsidian-spaced-repetition-recall/tree/update_fsrs_v5

**Comment by Newdea** [comment]
Still not understand that code, but it seems worked. Is that what you need？
Give it a try, and feedback is welcome.
[main_fixCodeblockRender.zip](https://github.com/user-attachments/files/16869720/main_fixCodeblockRender.zip)

![image](https://github.com/user-attachments/assets/ecc6c532-edc5-498b-a887-944dce91490c)
---
![image](https://github.com/user-attachments/assets/a8f06463-a368-4e0b-b244-3fc0d8a7c8b6)

**Comment by dryezl** [comment]
Problems fixed.
