### ISSUE TITLE
不同子标签的内容是否可以混合复习

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#8]
**Is your feature request related to a problem? Please describe.**
假设我现在需要复习的标签是#A，那么#A/b和#A/c也会纳入复习。我发现复习的时候，是先复习#A/b的内容，再到#A/c的。

**Describe the solution you'd like**
如果可以的话，我希望能够#A下面的内容混合复习（interleaving practice），这样效果会好一些的。另外如果需要针对子标签复习的话，我应该直接点击子标签的

**Additional context**

谢谢

**Comment by Newdea** [comment]
是卡片复习吧，因为要按标签分组，只能这样一组一组地复习。

想混合的话，建议复习就只用一个标签（如#flashcards），而内容区分用另外的标签（如#A/a/b/c）

**Comment by dryezl** [comment]
如果一个笔记（note）中里面用了两个复习标签（#Aflashcards和#Bflashcards），该笔记的复习卡牌只会出现在其中一个deck里面。

如果我平常采用#Allflashcard作为复习标签，标记所有需要复习的笔记，同时使用内容标签（#A/a, #A/b)，区分不同内容。
如果我需要单独复习某一部分时，考虑用#A替换#Allflashcard作为复习标签，这样不同的内容便可区分开来的。
不知道这样子，会不会影响复习内容的安排？

**Comment by Newdea** [comment]
应该不会影响复习时间排程的。
但如果有按标签记录到日志数据表格，会对后续使用optimizer有点影响，可以把两个标签都加上，或直接清空

![Screenshot_2023-08-10-12-38-14-410_md obsidian-edit](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/9208450/b6b55148-f671-452e-adb1-840982fdee29)
