### ISSUE TITLE
[Bug]: 重复生成大量block id

### ISSUE THREAD

**Issue by u2003** [open-spaced-repetition/obsidian-spaced-repetition-recall#81]
### Describe the bug

不知道为什么，打开写入blockid选项之后，已经加过高亮或者::的笔记都能被追踪到，但是有不小概率造成一些卡片后面的blockid爆炸性的增加，我没搞明白是怎么会触发的，因为不是所有卡片都会被重复追加blockid。
![CleanShot_2024-09-28_213005@2x](https://github.com/user-attachments/assets/664ed02d-3f64-413f-b161-f5a3b0bc8fc0)

### To Reproduce

Toggle Blocked

### Expected behavior

no repeated blockades

### OS of your device

Mac(Apple Silicon)

### Obsidian version

1.6.7

### Plugin version

1.12.5.11

**Comment by Newdea** [comment]
请提供文件md（注意删除个人信息）

**Comment by u2003** [comment]
[eo.md](https://github.com/user-attachments/files/17177824/eo.md)

**Comment by Newdea** [comment]
尝试了多次没有复现，请重新提供以下文件打包上传
1. md文件只保留会重复添加blockid的几个卡片，
2. 插件文件夹下的data.json文件





---Original---
From: ***@***.***&gt;
Sent at: 2024年9月29日(Sun) PM2:10
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-spaced-repetition/obsidian-spaced-repetition-recall] [Bug]: 重复生成大量block id (Issue #81)




 
eo.md

**Comment by u2003** [comment]
真的爆炸性增长，我的库快炸了都

**Comment by u2003** [comment]
这两天又给炸了

**Comment by u2003** [comment]
[General.md](https://github.com/user-attachments/files/17265862/General.md)
[2024-09-20_拉丁语词汇.md](https://github.com/user-attachments/files/17265863/2024-09-20_.md)
[data.json](https://github.com/user-attachments/files/17265864/data.json)

**Comment by u2003** [comment]
我猜测可能是因为连续多个::的行之间没有用多个空行隔开？？？

**Comment by u2003** [comment]
我在每个::所在的行之间都加了空行，block id还是爆炸性增长…… sigh

**Comment by Newdea** [comment]
是卡片文本解析有问题,临时解决方案是,修改下设置项:
![Screenshot at 2024-10-07 19-59-12](https://github.com/user-attachments/assets/13add6e6-4888-4398-b988-c61b72d0b740)

**Comment by u2003** [comment]
请问这一项具体是什么意思呢，插件在解析卡片的时候除了在md源码里加上block id之外，也没有看到有html注释呀

**Comment by Newdea** [comment]
是借用原插件的这个设置项,就是在blockid前的分隔符的区分(空格,或回车),
之前版本是都正常的,但最近几版原插件的代码重构的比较多,就出现这个不兼容的问题了
