### ISSUE TITLE
[FEAT]: 增加block id的方式更改为触发式

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#83]
### Is your feature request related to a problem? Please describe.

编辑文字时，obsidian有时会卡顿。如果编辑内容涉及到卡片时，obsidian卡顿后，会生成对应block id。有时候部分编辑内容会丢失。

### Describe the solution you'd like

现在的block id生成应该是定期扫描文件，捕捉到对应模式（pattern)后，生成block id。请问是否可以将这个过程改为触发式，比如启动复习时。
先叠个甲，可能是我的电脑配置太低，才会有这个问题的

**Comment by Newdea** [comment]
这个是更合理些,可以考虑

**Comment by dryezl** [comment]
插件更新后，优点是obsidian启动变快，CPU风扇高速旋转（有声音）变少。缺点是卡片复习启动时间变长。
我觉得这个缺点在对应的优点上来说，是可以接受的。
