### ISSUE TITLE
[Bug]: 无法开始卡片复习  

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#87]
### Describe the bug

插件更新版本后，卡片正常复习。
新增卡片后，点击卡片复习按钮，复习界面未在3min以内出现。
同时新增卡片未出现对应block id。
console显示报错如下
![image](https://github.com/user-attachments/assets/5a2f76e4-8e4c-4c6d-ac69-c9e123d13d97)

```html
plugin:obsidian-spaced-repetition-recall:33039 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isDummyScheduleForNewCard')
    at updateCardObjs (plugin:obsidian-spaced-repetition-recall:33039:33)
    at _ItemTrans.updateCardsSchedbyItems (plugin:obsidian-spaced-repetition-recall:33022:22)
    at _SRPlugin.loadNote (plugin:obsidian-spaced-repetition-recall:34586:15)
    at async eval (plugin:obsidian-spaced-repetition-recall:34473:22)
    at async Promise.all (index 1174)
    at async _SRPlugin.sync (plugin:obsidian-spaced-repetition-recall:34471:5)
    at async eval (plugin:obsidian-spaced-repetition-recall:34393:11)
updateCardObjs @ plugin:obsidian-spaced-repetition-recall:33039
updateCardsSchedbyItems @ plugin:obsidian-spaced-repetition-recall:33022
loadNote @ plugin:obsidian-spaced-repetition-recall:34586

```

### To Reproduce

如上

### Expected behavior

如上

### OS of your device

Win 10

### Obsidian version

1.1.9

### Plugin version

1.12.5.12

**Comment by Newdea** [comment]
昨天改出的bug,你试下这个看 
[main_fixblockid.zip](https://github.com/user-attachments/files/17341797/main_fixblockid.zip)


用着没问题的话,请反馈下,我笔记中没使用blockid,不确定效果如何,只是在测试库中是OK的.

**Comment by dryezl** [comment]
今天在没有安装上述更新的情况，上述问题自己消失了。这个真的很神奇。
迟点试一下更改之后的。感谢。

**Comment by dryezl** [comment]
应该是新增卡片的问题。我迟点试一下上面的更新版本。一开始的问题描述也做了相应修改。

**Comment by Newdea** [comment]
嗯，现在代码量太多了，维护起来有些难了，一不小心就容易引入bug😂

**Comment by dryezl** [comment]
新版本可以正常复习卡片，但和dataview冲突。
关闭spaced插件，重启后dataview就正常运行。

另外关闭之后重新启用spaced，obsidian会提示reindexing笔记

**Comment by Newdea** [comment]
> 但和dataview冲突。

没有遇到过,有影响的话, 就新开个issue详细描述下问题吧.

> 每次打开obsidian会提示indexing笔记。

这是OB自身的功能,是正常的.

**Comment by dryezl** [comment]
后来好像没有发现和dataview有冲突的。之前的问题应该是我写错dataview代码。
