### ISSUE TITLE
View statistics结果中Intervals和Eases均显示NaN

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#9]
![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/47209925/2b638e19-7de5-4cf6-b704-8ec02150d818)

![image](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/assets/47209925/a0295a7d-5800-42a4-8950-3c39777db10c)

View statistics结果中Intervals和Eases均显示NaN，Forcast和Card Types显示正常

**Comment by Newdea** [comment]
这部分功能一直没有动，是用的原插件的，可能是因添加算法后，参数不匹配导致的。我后续改下。

**Comment by Newdea** [comment]
问题已经改了，更新下就可以正常显示。
